from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextBoxSlot,
)

PROBLEM_ID = "P3_1_01_00040_00471"
PROBLEM_TITLE = "덧셈식의 크기 비교"

def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=900,
            height=220,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.instruction",
                    "slot.problem_1_number",
                    "slot.problem_1_left",
                    "slot.problem_1_blank",
                    "slot.problem_1_right",
                    "slot.problem_2_number",
                    "slot.problem_2_left",
                    "slot.problem_2_blank",
                    "slot.problem_2_right",
                ),
            ),
        ),
        slots=(
            TextBoxSlot(
                id="slot.instruction",
                x=38,
                y=22,
                width=824,
                height=38,
                text="크기를 비교하여 ○ 안에 >, =, <를 알맞게 써넣으시오.",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_number",
                x=40,
                y=76,
                width=55,
                height=38,
                text="(1)",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_left",
                x=105,
                y=76,
                width=90,
                height=38,
                text="532",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_blank",
                x=202,
                y=71,
                width=52,
                height=48,
                text="○",
                font_size=40,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_right",
                x=264,
                y=76,
                width=160,
                height=38,
                text="248+274",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_number",
                x=40,
                y=132,
                width=55,
                height=38,
                text="(2)",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_left",
                x=105,
                y=132,
                width=135,
                height=38,
                text="346+667",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_blank",
                x=247,
                y=127,
                width=52,
                height=48,
                text="○",
                font_size=40,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_right",
                x=309,
                y=132,
                width=160,
                height=38,
                text="428+585",
                font_size=24,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
        ),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC = {
    "problem_id": PROBLEM_ID,
    "problem_type": "multi_answer_expression_comparison",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "수학",
        "topic": "세 자리 수의 덧셈과 크기 비교",
        "language": "ko-KR",
    },
    "domain": {
        "objects": [
            {
                "id": "expression.problem_1_left",
                "type": "number_expression",
                "label": "첫 번째 비교의 왼쪽 수",
                "expression": "532",
                "value": 532,
            },
            {
                "id": "expression.problem_1_right",
                "type": "addition_expression",
                "label": "첫 번째 비교의 오른쪽 덧셈식",
                "expression": "248 + 274",
                "value": 522,
            },
            {
                "id": "comparison.problem_1",
                "type": "comparison",
                "label": "첫 번째 크기 비교",
                "left": "expression.problem_1_left",
                "right": "expression.problem_1_right",
                "operator": ">",
            },
            {
                "id": "expression.problem_2_left",
                "type": "addition_expression",
                "label": "두 번째 비교의 왼쪽 덧셈식",
                "expression": "346 + 667",
                "value": 1013,
            },
            {
                "id": "expression.problem_2_right",
                "type": "addition_expression",
                "label": "두 번째 비교의 오른쪽 덧셈식",
                "expression": "428 + 585",
                "value": 1013,
            },
            {
                "id": "comparison.problem_2",
                "type": "comparison",
                "label": "두 번째 크기 비교",
                "left": "expression.problem_2_left",
                "right": "expression.problem_2_right",
                "operator": "=",
            },
        ],
        "relations": [
            {
                "id": "relation.problem_1_left_greater_than_right",
                "type": "greater_than",
                "subject": "expression.problem_1_left",
                "object": "expression.problem_1_right",
            },
            {
                "id": "relation.problem_2_left_equals_right",
                "type": "equal_to",
                "subject": "expression.problem_2_left",
                "object": "expression.problem_2_right",
            },
        ],
    },
    "answer": {
        "value": [">", "="],
        "unit": "",
        "items": [
            {
                "id": "answer.problem_1",
                "value": ">",
            },
            {
                "id": "answer.problem_2",
                "value": "=",
            },
        ],
    },
}

SEMANTIC_OVERRIDE = SEMANTIC


SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'P3_1_01_00040_00471',
 'problem_type': 'multi_answer_expression_comparison',
 'inputs': {'target_label': '두 수 또는 두 덧셈식 사이에 알맞은 비교 기호 써넣기',
            'unit': '',
            'answer_type': 'comparison_operator',
            'allowed_operators': ['>', '=', '<'],
            'quantities': {'problem_1': {'left_expression': '532',
                                         'left_value': 532,
                                         'right_expression': '248 + 274',
                                         'right_value': 522},
                           'problem_2': {'left_expression': '346 + 667',
                                         'left_value': 1013,
                                         'right_expression': '428 + 585',
                                         'right_value': 1013}},
            'conditions': ['각 덧셈식의 값을 계산합니다.',
                           '왼쪽과 오른쪽의 크기를 비교합니다.',
                           '○ 안에 >, =, < 중 알맞은 기호를 씁니다.']},
 'given': [{'ref': 'comparison.problem_1',
            'value': {'left': {'expression': '532', 'value': 532},
                      'right': {'expression': '248 + 274', 'value': 522}}},
           {'ref': 'comparison.problem_2',
            'value': {'left': {'expression': '346 + 667', 'value': 1013},
                      'right': {'expression': '428 + 585', 'value': 1013}}}],
 'target': {'ref': 'answer.comparison_operators', 'type': 'operator_list'},
 'method': '각 덧셈식의 값을 계산한 뒤 두 값을 비교한다.',
 'plan': ['첫 번째 문제의 오른쪽 덧셈식 248+274를 계산한다.',
          '532와 계산한 값을 비교한다.',
          '두 번째 문제의 양쪽 덧셈식을 각각 계산한다.',
          '계산한 두 값을 비교한다.',
          '각 ○ 안에 알맞은 비교 기호를 쓴다.'],
 'steps': [{'id': 'step.problem_1_calculate_right',
            'expr': '248 + 274',
            'value': 522,
            'explanation': '첫 번째 문제의 오른쪽 덧셈식을 계산하면 522입니다.'},
           {'id': 'step.problem_1_compare',
            'expr': '532 > 522',
            'value': True,
            'explanation': '532는 522보다 크므로 알맞은 기호는 >입니다.'},
           {'id': 'step.problem_2_calculate_left',
            'expr': '346 + 667',
            'value': 1013,
            'explanation': '두 번째 문제의 왼쪽 덧셈식을 계산하면 1013입니다.'},
           {'id': 'step.problem_2_calculate_right',
            'expr': '428 + 585',
            'value': 1013,
            'explanation': '두 번째 문제의 오른쪽 덧셈식을 계산하면 1013입니다.'},
           {'id': 'step.problem_2_compare',
            'expr': '1013 = 1013',
            'value': True,
            'explanation': '두 덧셈식의 값이 같으므로 알맞은 기호는 =입니다.'}],
 'checks': [{'id': 'check.problem_1_right_sum',
             'expr': '248 + 274',
             'expected': 522,
             'actual': 522,
             'pass': True},
            {'id': 'check.problem_1_operator',
             'expr': '532 > 522',
             'expected': True,
             'actual': True,
             'pass': True},
            {'id': 'check.problem_2_left_sum',
             'expr': '346 + 667',
             'expected': 1013,
             'actual': 1013,
             'pass': True},
            {'id': 'check.problem_2_right_sum',
             'expr': '428 + 585',
             'expected': 1013,
             'actual': 1013,
             'pass': True},
            {'id': 'check.problem_2_operator',
             'expr': '1013 == 1013',
             'expected': True,
             'actual': True,
             'pass': True}],
 'answer': {'value': ['>', '='],
            'unit': '',
            'items': [{'id': 'answer.problem_1', 'value': '>'},
                      {'id': 'answer.problem_2', 'value': '='}]},
 'understanding': {'summary': 'Find 두 수 또는 두 덧셈식 사이에 알맞은 비교 기호 써넣기 using the given information.',
                   'facts': [{'ref': 'comparison.problem_1',
                              'label': 'problem 1',
                              'value': {'left': {'expression': '532', 'value': 532},
                                        'right': {'expression': '248 + 274', 'value': 522}},
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'comparison.problem_2',
                              'label': 'problem 2',
                              'value': {'left': {'expression': '346 + 667', 'value': 1013},
                                        'right': {'expression': '428 + 585', 'value': 1013}},
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.comparison_operators',
                                 'label': '두 수 또는 두 덧셈식 사이에 알맞은 비교 기호 써넣기',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': '각 덧셈식의 값을 계산한 뒤 두 값을 비교한다.',
                                'statement': '첫 번째 문제의 오른쪽 덧셈식 248+274를 계산한다.',
                                'symbolic': '248 + 274',
                                'uses': ['comparison.problem_1', 'comparison.problem_2'],
                                'result': 'answer.comparison_operators'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['problem 1',
                                                         'problem 2',
                                                         '두 수 또는 두 덧셈식 사이에 알맞은 비교 기호 써넣기'],
                                             'answer_index': 2}]}}

SOLVABLE.update({
    "inputs": {
        "target_label": "각 빈칸에 들어갈 비교 기호",
        "unit": "",
        "answer_type": "comparison_operator",
        "allowed_operators": [">", "=", "<"],
        "quantities": {
            "problem_1": {
                "left_expression": "532",
                "left_value": 532,
                "right_expression": "248 + 274",
                "right_value": 522,
            },
            "problem_2": {
                "left_expression": "346 + 667",
                "left_value": 1013,
                "right_expression": "428 + 585",
                "right_value": 1013,
            },
        },
        "conditions": [
            "각 식의 값을 계산합니다.",
            "왼쪽과 오른쪽의 크기를 비교합니다.",
            "빈칸에 >, =, < 중 알맞은 비교 기호를 씁니다.",
        ],
    },
    "given": [
        {
            "ref": "comparison.problem_1",
            "value": {
                "left": {"expression": "532", "value": 532},
                "right": {"expression": "248 + 274", "value": 522},
            },
        },
        {
            "ref": "comparison.problem_2",
            "value": {
                "left": {"expression": "346 + 667", "value": 1013},
                "right": {"expression": "428 + 585", "value": 1013},
            },
        },
    ],
    "target": {"ref": "answer.comparison_operators", "type": "operator_list"},
    "method": "양쪽 식의 값을 계산한 뒤 크기를 비교하여 알맞은 비교 기호를 고릅니다.",
    "plan": [
        "첫 번째 비교식의 오른쪽 식 248 + 274를 계산합니다.",
        "532와 계산한 값을 비교해 첫 번째 기호를 정합니다.",
        "두 번째 비교식의 왼쪽 식과 오른쪽 식을 각각 계산합니다.",
        "두 값을 비교해 두 번째 기호를 정합니다.",
    ],
    "steps": [
        {
            "id": "step.problem_1_calculate_right",
            "goal": "첫 번째 비교식의 오른쪽 값을 구합니다.",
            "uses": ["comparison.problem_1"],
            "expr": "248 + 274",
            "value": 522,
            "explanation": "첫 번째 문제에서 오른쪽 식 248 + 274를 계산하면 522입니다.",
        },
        {
            "id": "step.problem_1_compare",
            "goal": "첫 번째 빈칸에 들어갈 비교 기호를 정합니다.",
            "uses": ["comparison.problem_1"],
            "relation_expr": "532 > 522",
            "expr": "532 > 522",
            "value": True,
            "explanation": "532는 522보다 크므로 첫 번째 빈칸에는 >가 들어갑니다.",
        },
        {
            "id": "step.problem_2_calculate_left",
            "goal": "두 번째 비교식의 왼쪽 값을 구합니다.",
            "uses": ["comparison.problem_2"],
            "expr": "346 + 667",
            "value": 1013,
            "explanation": "두 번째 문제에서 왼쪽 식 346 + 667을 계산하면 1013입니다.",
        },
        {
            "id": "step.problem_2_calculate_right",
            "goal": "두 번째 비교식의 오른쪽 값을 구합니다.",
            "uses": ["comparison.problem_2"],
            "expr": "428 + 585",
            "value": 1013,
            "explanation": "두 번째 문제에서 오른쪽 식 428 + 585를 계산하면 1013입니다.",
        },
        {
            "id": "step.problem_2_compare",
            "goal": "두 번째 빈칸에 들어갈 비교 기호를 정합니다.",
            "uses": ["comparison.problem_2"],
            "relation_expr": "1013 = 1013",
            "expr": "1013 == 1013",
            "value": True,
            "explanation": "왼쪽과 오른쪽의 값이 모두 1013으로 같으므로 두 번째 빈칸에는 =가 들어갑니다.",
        },
    ],
    "checks": [
        {
            "id": "check.problem_1_right_sum",
            "description": "첫 번째 오른쪽 식을 다시 계산합니다.",
            "expr": "248 + 274",
            "expected": 522,
            "actual": 522,
            "pass": True,
        },
        {
            "id": "check.problem_1_operator",
            "description": "첫 번째 비교 결과가 >인지 확인합니다.",
            "expr": "532 > 522",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.problem_2_left_sum",
            "description": "두 번째 왼쪽 식을 다시 계산합니다.",
            "expr": "346 + 667",
            "expected": 1013,
            "actual": 1013,
            "pass": True,
        },
        {
            "id": "check.problem_2_right_sum",
            "description": "두 번째 오른쪽 식을 다시 계산합니다.",
            "expr": "428 + 585",
            "expected": 1013,
            "actual": 1013,
            "pass": True,
        },
        {
            "id": "check.problem_2_operator",
            "description": "두 번째 비교 결과가 =인지 확인합니다.",
            "expr": "1013 == 1013",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "value": [">", "="],
        "unit": "",
        "items": [
            {"id": "answer.problem_1", "value": ">"},
            {"id": "answer.problem_2", "value": "="},
        ],
    },
    "understanding": {
        "summary": "각 식의 값을 계산한 뒤, 왼쪽과 오른쪽을 비교해 빈칸에 알맞은 비교 기호를 쓰는 문제입니다.",
        "facts": [
            {
                "ref": "comparison.problem_1",
                "label": "첫 번째 비교식",
                "value": {"left": "532", "right": "248 + 274"},
                "unit": "",
                "source": "explicit",
            },
            {
                "ref": "comparison.problem_2",
                "label": "두 번째 비교식",
                "value": {"left": "346 + 667", "right": "428 + 585"},
                "unit": "",
                "source": "explicit",
            },
        ],
        "unknowns": [
            {
                "ref": "answer.comparison_operators",
                "label": "각 빈칸에 들어갈 비교 기호",
                "unit": "",
                "source": "unknown",
            }
        ],
        "relation": {
            "type": "expression_comparison",
            "statement": "양쪽 식의 값을 계산한 뒤, 큰 쪽과 같은 쪽을 판단해 >, =, < 중 알맞은 기호를 씁니다.",
            "symbolic": "left_value ? right_value",
            "uses": ["comparison.problem_1", "comparison.problem_2"],
            "result": "answer.comparison_operators",
        },
        "diagnostic_questions": [
            {
                "id": "understand.target",
                "type": "multiple_choice",
                "prompt": "이 문제에서 빈칸에 넣어야 하는 것은 무엇인가요?",
                "choices": ["계산 결과", "비교 기호", "단위"],
                "answer_index": 1,
            },
            {
                "id": "understand.method",
                "type": "multiple_choice",
                "prompt": "비교 기호를 고르기 전에 먼저 해야 할 일은 무엇인가요?",
                "choices": ["양쪽 식의 값을 계산합니다.", "가장 작은 숫자를 지웁니다.", "단위를 바꿉니다."],
                "answer_index": 0,
            },
        ],
        "student_restatement": {
            "prompt": "문제의 뜻을 말해 볼까요?",
            "template": "각 비교식의 양쪽 값을 계산한 뒤 {symbols} 중 알맞은 기호를 고릅니다.",
            "answer": "각 비교식의 양쪽 값을 계산한 뒤 >, =, < 중 알맞은 기호를 고릅니다.",
        },
    },
})

SEMANTIC_ANSWER = SOLVABLE["answer"]
