from __future__ import annotations

from modu_math.dsl import (
    BlankSlot,
    Canvas,
    Group,
    LineSlot,
    ProblemTemplate,
    Region,
    TextBoxSlot,
    TextSlot,
)

PROBLEM_ID = "P3_1_01_00040_02156"
PROBLEM_TITLE = "받아올림하며 세 자리 수의 덧셈 계산"


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=760,
            height=250,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.process",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.instruction",
                    "slot.stage1.carry",
                    "slot.stage1.top",
                    "slot.stage1.plus",
                    "slot.stage1.bottom",
                    "slot.stage1.line",
                    "slot.stage1.answer_ones",
                    "slot.arrow_1",
                    "slot.stage2.carry_hundreds",
                    "slot.stage2.carry_tens",
                    "slot.stage2.top",
                    "slot.stage2.plus",
                    "slot.stage2.bottom",
                    "slot.stage2.line",
                    "slot.stage2.answer_tens",
                    "slot.stage2.answer_ones",
                    "slot.arrow_2",
                    "slot.stage3.carry_hundreds",
                    "slot.stage3.carry_tens",
                    "slot.stage3.top",
                    "slot.stage3.plus",
                    "slot.stage3.bottom",
                    "slot.stage3.line",
                    "slot.stage3.answer_hundreds",
                    "slot.stage3.answer_tens",
                    "slot.stage3.answer_ones",
                ),
            ),
        ),
        slots=(
            TextBoxSlot(
                id="slot.instruction",
                x=24,
                y=18.994,
                width=278,
                height=66,
                text="□ 안에 알맞은 수를 써넣으시오.",
                font_size=23,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
                line_height=1.25,
            ),
            # =========================================================
            # 1단계: 일의 자리 계산
            # 4 + 9 = 13 → 3을 쓰고 1을 받아올림
            # =========================================================
            TextSlot(
                id="slot.stage1.carry",
                text="□",
                prompt="일의 자리에서 십의 자리로 받아올림할 수",
                x=139,
                y=96.955,
                font_size=24,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage1.top",
                text="554",
                prompt="첫 번째 단계의 위 수 554",
                x=161,
                y=132.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage1.plus",
                text="+",
                prompt="첫 번째 단계의 덧셈 기호",
                x=85,
                y=181.959,
                font_size=28,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage1.bottom",
                text="269",
                prompt="첫 번째 단계의 아래 수 269",
                x=161,
                y=181.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            LineSlot(
                id="slot.stage1.line",
                prompt="첫 번째 단계의 계산선",
                x1=62,
                y1=200.959,
                x2=175,
                y2=200.959,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.stage1.answer_ones",
                text="□",
                prompt="첫 번째 단계에서 구한 일의 자리 숫자",
                x=151,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.arrow_1",
                text="⇒",
                prompt="첫 번째 단계에서 두 번째 단계로 진행하는 화살표",
                x=217,
                y=178.959,
                font_size=31,
                anchor="middle",
                fill="#111111",
            ),
            # =========================================================
            # 2단계: 십의 자리 계산
            # 5 + 6 + 1 = 12 → 2를 쓰고 1을 받아올림
            # =========================================================
            TextSlot(
                id="slot.stage2.carry_hundreds",
                text="□",
                prompt="십의 자리에서 백의 자리로 받아올림할 수",
                x=314,
                y=97.955,
                font_size=24,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage2.carry_tens",
                text="□",
                prompt="일의 자리에서 십의 자리로 받아올림한 수",
                x=337,
                y=97.954,
                font_size=24,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage2.top",
                text="554",
                prompt="두 번째 단계의 위 수 554",
                x=355,
                y=132.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage2.plus",
                text="+",
                prompt="두 번째 단계의 덧셈 기호",
                x=279,
                y=181.959,
                font_size=28,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage2.bottom",
                text="269",
                prompt="두 번째 단계의 아래 수 269",
                x=355,
                y=181.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            LineSlot(
                id="slot.stage2.line",
                prompt="두 번째 단계의 계산선",
                x1=256,
                y1=200.959,
                x2=369,
                y2=200.959,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.stage2.answer_tens",
                text="□",
                prompt="두 번째 단계에서 구한 십의 자리 숫자",
                x=315,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage2.answer_ones",
                text="□",
                prompt="두 번째 단계에서 이미 구한 일의 자리 숫자",
                x=347,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.arrow_2",
                text="⇒",
                prompt="두 번째 단계에서 세 번째 단계로 진행하는 화살표",
                x=411,
                y=178.959,
                font_size=31,
                anchor="middle",
                fill="#111111",
            ),
            # =========================================================
            # 3단계: 백의 자리 계산 및 완성
            # 5 + 2 + 1 = 8 → 823
            # =========================================================
            TextSlot(
                id="slot.stage3.carry_hundreds",
                text="□",
                prompt="십의 자리에서 백의 자리로 받아올림한 수",
                x=501,
                y=103.951,
                font_size=24,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.carry_tens",
                text="□",
                prompt="일의 자리에서 십의 자리로 받아올림한 수",
                x=526,
                y=103.951,
                font_size=24,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.top",
                text="554",
                prompt="세 번째 단계의 위 수 554",
                x=549,
                y=132.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.plus",
                text="+",
                prompt="세 번째 단계의 덧셈 기호",
                x=473,
                y=181.959,
                font_size=28,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.bottom",
                text="269",
                prompt="세 번째 단계의 아래 수 269",
                x=549,
                y=181.959,
                font_size=29,
                anchor="end",
                fill="#111111",
            ),
            LineSlot(
                id="slot.stage3.line",
                prompt="세 번째 단계의 계산선",
                x1=450,
                y1=200.959,
                x2=563,
                y2=200.959,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.stage3.answer_hundreds",
                text="□",
                prompt="최종 답의 백의 자리 숫자",
                x=479,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.answer_tens",
                text="□",
                prompt="최종 답의 십의 자리 숫자",
                x=511,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            TextSlot(
                id="slot.stage3.answer_ones",
                text="□",
                prompt="최종 답의 일의 자리 숫자",
                x=543,
                y=240.959,
                font_size=29,
                anchor="middle",
                fill="#111111",
            ),
            # 실제 정답 데이터용 빈칸 슬롯
            BlankSlot(
                id="answer.stage1.carry",
                prompt="첫 번째 단계의 받아올림 수",
                answer_key="1",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage1.ones",
                prompt="첫 번째 단계의 일의 자리",
                answer_key="3",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage2.carry_hundreds",
                prompt="두 번째 단계의 받아올림 수",
                answer_key="1",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage2.carry_tens",
                prompt="두 번째 단계에 표시된 이전 받아올림 수",
                answer_key="1",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage2.tens",
                prompt="두 번째 단계의 십의 자리",
                answer_key="2",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage2.ones",
                prompt="두 번째 단계의 일의 자리",
                answer_key="3",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage3.carry_hundreds",
                prompt="세 번째 단계에 표시된 백의 자리 받아올림 수",
                answer_key="1",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage3.carry_tens",
                prompt="세 번째 단계에 표시된 십의 자리 받아올림 수",
                answer_key="1",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage3.hundreds",
                prompt="최종 답의 백의 자리",
                answer_key="8",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage3.tens",
                prompt="최종 답의 십의 자리",
                answer_key="2",
                placeholder="",
            ),
            BlankSlot(
                id="answer.stage3.ones",
                prompt="최종 답의 일의 자리",
                answer_key="3",
                placeholder="",
            ),
        ),
        diagrams=(),
        groups=(
            Group(
                id="group.stage1",
                role="vertical_addition_step",
                member_ids=(
                    "slot.stage1.carry",
                    "slot.stage1.top",
                    "slot.stage1.plus",
                    "slot.stage1.bottom",
                    "slot.stage1.line",
                    "slot.stage1.answer_ones",
                ),
            ),
            Group(
                id="group.stage2",
                role="vertical_addition_step",
                member_ids=(
                    "slot.stage2.carry_hundreds",
                    "slot.stage2.carry_tens",
                    "slot.stage2.top",
                    "slot.stage2.plus",
                    "slot.stage2.bottom",
                    "slot.stage2.line",
                    "slot.stage2.answer_tens",
                    "slot.stage2.answer_ones",
                ),
            ),
            Group(
                id="group.stage3",
                role="vertical_addition_step",
                member_ids=(
                    "slot.stage3.carry_hundreds",
                    "slot.stage3.carry_tens",
                    "slot.stage3.top",
                    "slot.stage3.plus",
                    "slot.stage3.bottom",
                    "slot.stage3.line",
                    "slot.stage3.answer_hundreds",
                    "slot.stage3.answer_tens",
                    "slot.stage3.answer_ones",
                ),
            ),
        ),
        constraints=(),
        tags=(
            "grade-3",
            "addition",
            "three-digit-addition",
            "carrying",
            "step-by-step",
            "vertical-calculation",
        ),
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC_OVERRIDE = {
    "problem_id": PROBLEM_ID,
    "problem_type": "stepwise_vertical_addition_with_carrying",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "수학",
        "topic": "세 자리 수의 덧셈",
        "language": "ko-KR",
        "question": "554와 269를 받아올림하며 차례대로 계산합니다.",
    },
    "domain": {
        "objects": [
            {
                "id": "calculation.main",
                "type": "vertical_addition",
                "label": "554와 269의 덧셈",
                "addends": [554, 269],
            },
            {
                "id": "stage.ones",
                "type": "place_value_step",
                "place": "ones",
                "equation": "4 + 9 = 13",
                "written_digit": 3,
                "carry": 1,
            },
            {
                "id": "stage.tens",
                "type": "place_value_step",
                "place": "tens",
                "equation": "5 + 6 + 1 = 12",
                "written_digit": 2,
                "carry": 1,
            },
            {
                "id": "stage.hundreds",
                "type": "place_value_step",
                "place": "hundreds",
                "equation": "5 + 2 + 1 = 8",
                "written_digit": 8,
                "carry": 0,
            },
        ],
        "relations": [
            {
                "id": "relation.sum",
                "type": "addition",
                "from_ids": ["number.554", "number.269"],
                "to_id": "answer.total",
                "equation": "554 + 269 = 823",
            }
        ],
    },
    "answer": {
        "blanks": [
            {"id": "answer.stage1.carry", "type": "digit", "value": 1},
            {"id": "answer.stage1.ones", "type": "digit", "value": 3},
            {"id": "answer.stage2.carry_hundreds", "type": "digit", "value": 1},
            {"id": "answer.stage2.carry_tens", "type": "digit", "value": 1},
            {"id": "answer.stage2.tens", "type": "digit", "value": 2},
            {"id": "answer.stage2.ones", "type": "digit", "value": 3},
            {"id": "answer.stage3.carry_hundreds", "type": "digit", "value": 1},
            {"id": "answer.stage3.carry_tens", "type": "digit", "value": 1},
            {"id": "answer.stage3.hundreds", "type": "digit", "value": 8},
            {"id": "answer.stage3.tens", "type": "digit", "value": 2},
            {"id": "answer.stage3.ones", "type": "digit", "value": 3},
        ],
        "choices": [],
        "answer_key": [
            {"blank_id": "answer.stage1.carry", "value": 1},
            {"blank_id": "answer.stage1.ones", "value": 3},
            {"blank_id": "answer.stage2.carry_hundreds", "value": 1},
            {"blank_id": "answer.stage2.carry_tens", "value": 1},
            {"blank_id": "answer.stage2.tens", "value": 2},
            {"blank_id": "answer.stage2.ones", "value": 3},
            {"blank_id": "answer.stage3.carry_hundreds", "value": 1},
            {"blank_id": "answer.stage3.carry_tens", "value": 1},
            {"blank_id": "answer.stage3.hundreds", "value": 8},
            {"blank_id": "answer.stage3.tens", "value": 2},
            {"blank_id": "answer.stage3.ones", "value": 3},
        ],
        "value": 823,
    },
}


SOLVABLE = {
    "schema": "modu.solvable.v1.2",
    "problem_id": PROBLEM_ID,
    "problem_type": "stepwise_vertical_addition_with_carrying",
    "inputs": {
        "target_label": "554와 269의 합",
        "quantities": {
            "first_addend": 554,
            "second_addend": 269,
        },
        "conditions": [
            "같은 자리의 숫자끼리 맞추어 더합니다.",
            "일의 자리부터 차례대로 계산합니다.",
            "각 자리의 합이 10 이상이면 바로 윗자리로 1을 받아올림합니다.",
        ],
    },
    "given": [
        {"ref": "number.554", "value": 554},
        {"ref": "number.269", "value": 269},
    ],
    "target": {
        "ref": "answer.total",
        "type": "sum",
    },
    "understanding": {
        "summary": "554와 269를 일의 자리부터 더하고, 받아올림을 다음 자리에 반영하는 문제입니다.",
        "facts": [
            {
                "ref": "rule.place_value_alignment",
                "label": "자리 맞추기",
                "source": "inferred",
                "meaning": "일의 자리, 십의 자리, 백의 자리를 맞추어 계산합니다.",
            },
            {
                "ref": "rule.carrying",
                "label": "받아올림",
                "source": "inferred",
                "meaning": "한 자리의 합이 10 이상이면 1을 다음 자리로 올립니다.",
            },
        ],
        "unknowns": [
            {"ref": "stage.ones.carry", "label": "일의 자리에서 받아올림할 수"},
            {"ref": "stage.ones.digit", "label": "합의 일의 자리"},
            {"ref": "stage.tens.carry", "label": "십의 자리에서 받아올림할 수"},
            {"ref": "stage.tens.digit", "label": "합의 십의 자리"},
            {"ref": "stage.hundreds.digit", "label": "합의 백의 자리"},
        ],
        "relation": {
            "type": "place_value_addition",
            "statement": "각 자리의 수와 이전 자리에서 받아올림한 수를 더합니다.",
            "symbolic": "ones → tens → hundreds",
            "uses": ["rule.place_value_alignment", "rule.carrying"],
            "result": "answer.total",
        },
    },
    "method": "vertical_addition_with_carrying",
    "plan": [
        "일의 자리 4와 9를 더합니다.",
        "일의 자리에서 생긴 받아올림 1을 십의 자리에 더합니다.",
        "십의 자리에서 생긴 받아올림 1을 백의 자리에 더합니다.",
        "각 자리에서 구한 숫자를 차례대로 써서 합을 완성합니다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "goal": "일의 자리를 계산합니다.",
            "uses": ["number.554", "number.269"],
            "expr": "4 + 9 = 13",
            "value": {
                "written_digit": 3,
                "carry": 1,
                "ref": "stage.ones",
            },
            "explanation": "3을 일의 자리에 쓰고 1을 십의 자리로 받아올림합니다.",
        },
        {
            "id": "step.2",
            "goal": "십의 자리를 계산합니다.",
            "uses": ["stage.ones", "number.554", "number.269"],
            "expr": "5 + 6 + 1 = 12",
            "value": {
                "written_digit": 2,
                "carry": 1,
                "ref": "stage.tens",
            },
            "explanation": "2를 십의 자리에 쓰고 1을 백의 자리로 받아올림합니다.",
        },
        {
            "id": "step.3",
            "goal": "백의 자리를 계산하여 답을 완성합니다.",
            "uses": ["stage.tens", "number.554", "number.269"],
            "expr": "5 + 2 + 1 = 8",
            "value": {
                "written_digit": 8,
                "sum": 823,
                "ref": "answer.total",
            },
            "explanation": "백의 자리에 8을 쓰면 554 + 269 = 823입니다.",
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "description": "823에서 269를 빼서 첫 번째 수가 나오는지 확인합니다.",
            "expr": "823 - 269",
            "expected": 554,
            "actual": 554,
            "pass": True,
        },
        {
            "id": "check.2",
            "description": "554와 269를 어림하여 합의 크기가 알맞은지 확인합니다.",
            "expr": "550 + 270 ≈ 820",
            "expected": "약 820",
            "actual": 823,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": SEMANTIC_OVERRIDE["answer"]["blanks"],
        "choices": [],
        "answer_key": SEMANTIC_OVERRIDE["answer"]["answer_key"],
        "value": 823,
        "sentence": "554와 269의 합은 823입니다.",
    },
}

SOLVABLE.update(
    {
        "inputs": {
            "target_label": "554와 269의 합",
            "unit": "",
            "quantities": {
                "first_addend": 554,
                "second_addend": 269,
            },
            "conditions": [
                "같은 자리의 숫자끼리 맞추어 더합니다.",
                "일의 자리부터 차례대로 계산합니다.",
                "각 자리의 합이 10 이상이면 바로 윗자리로 1을 받아올림합니다.",
            ],
        },
        "given": [
            {"ref": "number.554", "value": 554},
            {"ref": "number.269", "value": 269},
        ],
        "target": {
            "ref": "answer.total",
            "type": "sum",
        },
        "understanding": {
            "summary": "554와 269를 세로셈으로 더하면서 받아올림을 반영해 합을 구하는 문제입니다.",
            "facts": [
                {
                    "ref": "number.554",
                    "label": "첫 번째 수",
                    "value": 554,
                    "unit": "",
                    "source": "explicit",
                },
                {
                    "ref": "number.269",
                    "label": "두 번째 수",
                    "value": 269,
                    "unit": "",
                    "source": "explicit",
                },
                {
                    "ref": "rule.carrying",
                    "label": "받아올림",
                    "value": "각 자리의 합이 10 이상이면 십의 자리 숫자는 바로 윗자리로 올립니다.",
                    "unit": "",
                    "source": "inferred",
                },
            ],
            "unknowns": [
                {
                    "ref": "answer.total",
                    "label": "554와 269의 합",
                    "unit": "",
                    "source": "unknown",
                }
            ],
            "relation": {
                "type": "place_value_addition",
                "statement": "일의 자리, 십의 자리, 백의 자리 순서로 더하고 받아올림을 다음 자리에 더합니다.",
                "symbolic": "554 + 269",
                "uses": ["number.554", "number.269", "rule.carrying"],
                "result": "answer.total",
            },
            "diagnostic_questions": [
                {
                    "id": "understand.target",
                    "type": "multiple_choice",
                    "prompt": "이 문제에서 구해야 하는 것은 무엇인가요?",
                    "choices": ["554와 269의 합", "554와 269의 차", "두 수의 곱"],
                    "answer_index": 0,
                },
                {
                    "id": "understand.start_place",
                    "type": "multiple_choice",
                    "prompt": "세로셈 덧셈은 어느 자리부터 계산하나요?",
                    "choices": ["일의 자리", "십의 자리", "백의 자리"],
                    "answer_index": 0,
                },
            ],
            "student_restatement": {
                "prompt": "문제의 뜻을 말해 볼까요?",
                "template": "{a}와 {b}를 같은 자리끼리 맞추어 더하고 받아올림을 반영해 합을 구합니다.",
                "answer": "554와 269를 같은 자리끼리 맞추어 더하고 받아올림을 반영해 합을 구합니다.",
            },
        },
        "method": "세로셈에서 같은 자리끼리 더하고 받아올림을 다음 자리에 더합니다.",
        "plan": [
            "일의 자리 4와 9를 더해 일의 자리 숫자와 받아올림을 정합니다.",
            "십의 자리 5와 6에 받아올림 1을 더해 십의 자리 숫자와 받아올림을 정합니다.",
            "백의 자리 5와 2에 받아올림 1을 더해 백의 자리 숫자를 정합니다.",
            "각 자리 숫자를 모아 합을 완성합니다.",
        ],
        "steps": [
            {
                "id": "step.ones",
                "goal": "일의 자리를 계산합니다.",
                "uses": ["number.554", "number.269"],
                "expr": "4 + 9",
                "value": 13,
                "explanation": "일의 자리에서 4 + 9 = 13이므로 3을 쓰고 1을 십의 자리로 받아올림합니다.",
            },
            {
                "id": "step.tens",
                "goal": "십의 자리를 계산합니다.",
                "uses": ["number.554", "number.269", "step.ones"],
                "expr": "5 + 6 + 1",
                "value": 12,
                "explanation": "십의 자리에서 5 + 6에 받아올림 1을 더하면 12이므로 2를 쓰고 1을 백의 자리로 받아올림합니다.",
            },
            {
                "id": "step.hundreds",
                "goal": "백의 자리를 계산합니다.",
                "uses": ["number.554", "number.269", "step.tens"],
                "expr": "5 + 2 + 1",
                "value": 8,
                "explanation": "백의 자리에서 5 + 2에 받아올림 1을 더하면 8입니다.",
            },
            {
                "id": "step.total",
                "goal": "합을 완성합니다.",
                "uses": ["step.ones", "step.tens", "step.hundreds"],
                "expr": "554 + 269",
                "value": 823,
                "explanation": "백의 자리부터 8, 2, 3을 차례로 쓰면 554 + 269 = 823입니다.",
            },
        ],
        "checks": [
            {
                "id": "check.subtract",
                "description": "합 823에서 269를 빼면 554가 되는지 확인합니다.",
                "expr": "823 - 269",
                "expected": 554,
                "actual": 554,
                "pass": True,
            },
            {
                "id": "check.estimate",
                "description": "554 + 269는 550 + 270과 가까우므로 823은 알맞은 크기의 답입니다.",
                "expr": "550 + 270",
                "expected": 820,
                "actual": 820,
                "pass": True,
            },
        ],
        "answer": {
            "blanks": SEMANTIC_OVERRIDE["answer"]["blanks"],
            "choices": [],
            "answer_key": SEMANTIC_OVERRIDE["answer"]["answer_key"],
            "value": 823,
            "unit": "",
            "sentence": "554와 269의 합은 823입니다.",
        },
    }
)

SEMANTIC_OVERRIDE["answer"] = SOLVABLE["answer"]
SEMANTIC_ANSWER = SOLVABLE["answer"]
