from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextBoxSlot,
)


PROBLEM_ID = "P3_1_01_00040_02154"
PROBLEM_TITLE = "받아올림이 있는 세 자리 수의 덧셈"


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=900,
            height=220,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.instruction",),
            ),
            Region(
                id="region.problem_1",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.problem_1_number",
                    "slot.problem_1_carry_hundreds",
                    "slot.problem_1_carry_tens",
                    "slot.problem_1_first_addend",
                    "slot.problem_1_plus_sign",
                    "slot.problem_1_second_addend",
                    "slot.problem_1_line",
                    "slot.problem_1_answer_thousands",
                    "slot.problem_1_answer_hundreds",
                    "slot.problem_1_answer_tens",
                    "slot.problem_1_answer_ones",
                ),
            ),
            Region(
                id="region.problem_2",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.problem_2_number",
                    "slot.problem_2_carry_hundreds",
                    "slot.problem_2_carry_tens",
                    "slot.problem_2_first_addend",
                    "slot.problem_2_plus_sign",
                    "slot.problem_2_second_addend",
                    "slot.problem_2_line",
                    "slot.problem_2_answer_thousands",
                    "slot.problem_2_answer_hundreds",
                    "slot.problem_2_answer_tens",
                    "slot.problem_2_answer_ones",
                ),
            ),
        ),
        slots=(
            TextBoxSlot(
                id="slot.instruction",
                x=20,
                y=8,
                width=840,
                height=34,
                text="□ 안에 알맞은 수를 써넣으시오.",
                font_size=23,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),

            # (1) 529 + 775
            TextBoxSlot(
                id="slot.problem_1_number",
                x=24,
                y=72,
                width=34,
                height=32,
                text="(1)",
                font_size=22,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_carry_hundreds",
                x=63,
                y=38,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_carry_tens",
                x=94,
                y=38,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_first_addend",
                x=55,
                y=62,
                width=104,
                height=32,
                text="5 2 9",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_plus_sign",
                x=41,
                y=98,
                width=24,
                height=32,
                text="+",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_second_addend",
                x=55,
                y=98,
                width=104,
                height=32,
                text="7 7 5",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_line",
                x=43,
                y=126,
                width=122,
                height=18,
                text="───────",
                font_size=20,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_thousands",
                x=43,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_hundreds",
                x=74,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_tens",
                x=105,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_1_answer_ones",
                x=136,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),

            # (2) 257 + 769
            TextBoxSlot(
                id="slot.problem_2_number",
                x=137,
                y=72,
                width=34,
                height=32,
                text="(2)",
                font_size=22,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_carry_hundreds",
                x=180,
                y=38,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_carry_tens",
                x=211,
                y=38,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_first_addend",
                x=172,
                y=62,
                width=104,
                height=32,
                text="2 5 7",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_plus_sign",
                x=158,
                y=98,
                width=24,
                height=32,
                text="+",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_second_addend",
                x=172,
                y=98,
                width=104,
                height=32,
                text="7 6 9",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_line",
                x=160,
                y=126,
                width=122,
                height=18,
                text="───────",
                font_size=20,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_thousands",
                x=160,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_hundreds",
                x=191,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_tens",
                x=222,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.problem_2_answer_ones",
                x=253,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
        ),
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC = {
    "problem_id": PROBLEM_ID,
    "problem_type": "multi_answer_vertical_addition",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "수학",
        "topic": "받아올림이 있는 세 자리 수의 덧셈",
        "language": "ko-KR",
    },
    "domain": {
        "objects": [
            {
                "id": "addition.problem_1",
                "type": "vertical_addition",
                "label": "첫 번째 세로셈",
                "first_addend": 529,
                "second_addend": 775,
                "sum": 1304,
            },
            {
                "id": "addition.problem_2",
                "type": "vertical_addition",
                "label": "두 번째 세로셈",
                "first_addend": 257,
                "second_addend": 769,
                "sum": 1026,
            },
        ],
        "relations": [
            {
                "id": "relation.problem_1_sum",
                "type": "sum_of",
                "subject": "addition.problem_1",
                "values": [529, 775],
            },
            {
                "id": "relation.problem_2_sum",
                "type": "sum_of",
                "subject": "addition.problem_2",
                "values": [257, 769],
            },
        ],
    },
    "answer": {
        "value": [1, 1, 1, 3, 0, 4, 1, 1, 1, 0, 2, 6],
        "unit": "",
        "items": [
            {"id": "answer.problem_1.carry_hundreds", "value": 1},
            {"id": "answer.problem_1.carry_tens", "value": 1},
            {"id": "answer.problem_1.thousands", "value": 1},
            {"id": "answer.problem_1.hundreds", "value": 3},
            {"id": "answer.problem_1.tens", "value": 0},
            {"id": "answer.problem_1.ones", "value": 4},
            {"id": "answer.problem_2.carry_hundreds", "value": 1},
            {"id": "answer.problem_2.carry_tens", "value": 1},
            {"id": "answer.problem_2.thousands", "value": 1},
            {"id": "answer.problem_2.hundreds", "value": 0},
            {"id": "answer.problem_2.tens", "value": 2},
            {"id": "answer.problem_2.ones", "value": 6},
        ],
    },
}

SEMANTIC_OVERRIDE = SEMANTIC


SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'P3_1_01_00040_02154',
 'problem_type': 'multi_answer_vertical_addition',
 'inputs': {'target_label': '두 세로셈의 받아올림한 수와 계산 결과',
            'unit': '',
            'answer_type': 'digit_list',
            'quantities': {'problem_1': {'first_addend': 529, 'second_addend': 775},
                           'problem_2': {'first_addend': 257, 'second_addend': 769}},
            'conditions': ['일의 자리부터 차례대로 계산합니다.',
                           '각 자리의 합이 10 이상이면 바로 윗자리로 1을 받아올림합니다.',
                           '받아올림한 수와 덧셈 결과의 각 자리 숫자를 네모 안에 씁니다.']},
 'given': [{'ref': 'addition.problem_1', 'value': {'first_addend': 529, 'second_addend': 775}},
           {'ref': 'addition.problem_2', 'value': {'first_addend': 257, 'second_addend': 769}}],
 'target': {'ref': 'answer.vertical_addition_blanks', 'type': 'digit_list'},
 'method': '각 세로셈에서 일의 자리부터 더하고, 받아올림한 수를 바로 윗자리 계산에 포함한다.',
 'plan': ['첫 번째 세로셈 529+775를 일의 자리부터 계산한다.',
          '첫 번째 세로셈의 받아올림한 수와 결과를 쓴다.',
          '두 번째 세로셈 257+769를 일의 자리부터 계산한다.',
          '두 번째 세로셈의 받아올림한 수와 결과를 쓴다.'],
 'steps': [{'id': 'step.problem_1.add_ones',
            'expr': '9 + 5',
            'value': 14,
            'explanation': '일의 자리에서 9와 5를 더하면 14이므로 4를 쓰고 1을 받아올림합니다.'},
           {'id': 'step.problem_1.add_tens',
            'expr': '2 + 7 + 1',
            'value': 10,
            'explanation': '십의 자리에서 2와 7에 받아올림한 1을 더하면 10이므로 0을 쓰고 1을 받아올림합니다.'},
           {'id': 'step.problem_1.add_hundreds',
            'expr': '5 + 7 + 1',
            'value': 13,
            'explanation': '백의 자리에서 5와 7에 받아올림한 1을 더하면 13이므로 13을 앞에 씁니다.'},
           {'id': 'step.problem_1.compose_sum',
            'expr': '529 + 775',
            'value': 1304,
            'explanation': '첫 번째 세로셈의 결과는 1304입니다.'},
           {'id': 'step.problem_2.add_ones',
            'expr': '7 + 9',
            'value': 16,
            'explanation': '일의 자리에서 7과 9를 더하면 16이므로 6을 쓰고 1을 받아올림합니다.'},
           {'id': 'step.problem_2.add_tens',
            'expr': '5 + 6 + 1',
            'value': 12,
            'explanation': '십의 자리에서 5와 6에 받아올림한 1을 더하면 12이므로 2를 쓰고 1을 받아올림합니다.'},
           {'id': 'step.problem_2.add_hundreds',
            'expr': '2 + 7 + 1',
            'value': 10,
            'explanation': '백의 자리에서 2와 7에 받아올림한 1을 더하면 10이므로 10을 앞에 씁니다.'},
           {'id': 'step.problem_2.compose_sum',
            'expr': '257 + 769',
            'value': 1026,
            'explanation': '두 번째 세로셈의 결과는 1026입니다.'}],
 'checks': [{'id': 'check.problem_1.total',
             'expr': '529 + 775',
             'expected': 1304,
             'actual': 1304,
             'pass': True},
            {'id': 'check.problem_1.inverse',
             'expr': '1304 - 775',
             'expected': 529,
             'actual': 529,
             'pass': True},
            {'id': 'check.problem_2.total',
             'expr': '257 + 769',
             'expected': 1026,
             'actual': 1026,
             'pass': True},
            {'id': 'check.problem_2.inverse',
             'expr': '1026 - 769',
             'expected': 257,
             'actual': 257,
             'pass': True}],
 'answer': {'value': [1, 1, 1, 3, 0, 4, 1, 1, 1, 0, 2, 6],
            'unit': '',
            'items': [{'id': 'answer.problem_1.carry_hundreds', 'value': 1},
                      {'id': 'answer.problem_1.carry_tens', 'value': 1},
                      {'id': 'answer.problem_1.thousands', 'value': 1},
                      {'id': 'answer.problem_1.hundreds', 'value': 3},
                      {'id': 'answer.problem_1.tens', 'value': 0},
                      {'id': 'answer.problem_1.ones', 'value': 4},
                      {'id': 'answer.problem_2.carry_hundreds', 'value': 1},
                      {'id': 'answer.problem_2.carry_tens', 'value': 1},
                      {'id': 'answer.problem_2.thousands', 'value': 1},
                      {'id': 'answer.problem_2.hundreds', 'value': 0},
                      {'id': 'answer.problem_2.tens', 'value': 2},
                      {'id': 'answer.problem_2.ones', 'value': 6}]},
 'understanding': {'summary': 'Find 두 세로셈의 받아올림한 수와 계산 결과 using the given information.',
                   'facts': [{'ref': 'addition.problem_1',
                              'label': 'problem 1',
                              'value': {'first_addend': 529, 'second_addend': 775},
                              'unit': '',
                              'source': 'explicit'},
                             {'ref': 'addition.problem_2',
                              'label': 'problem 2',
                              'value': {'first_addend': 257, 'second_addend': 769},
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.vertical_addition_blanks',
                                 'label': '두 세로셈의 받아올림한 수와 계산 결과',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': '각 세로셈에서 일의 자리부터 더하고, 받아올림한 수를 바로 윗자리 계산에 포함한다.',
                                'statement': '첫 번째 세로셈 529+775를 일의 자리부터 계산한다.',
                                'symbolic': '9 + 5',
                                'uses': ['addition.problem_1', 'addition.problem_2'],
                                'result': 'answer.vertical_addition_blanks'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['problem 1',
                                                         'problem 2',
                                                         '두 세로셈의 받아올림한 수와 계산 결과'],
                                             'answer_index': 2}]}}

SEMANTIC_ANSWER = SOLVABLE["answer"]
