from __future__ import annotations

from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextBoxSlot,
)

PROBLEM_ID = "P3_1_01_00040_02153"
PROBLEM_TITLE = "받아올림 과정을 나타낸 세 자리 수의 덧셈"


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id=PROBLEM_ID,
        title=PROBLEM_TITLE,
        canvas=Canvas(
            width=900,
            height=210,
            coordinate_mode="logical",
        ),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.instruction",
                ),
            ),
            Region(
                id="region.step_1",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.step_1_carry_tens",
                    "slot.step_1_first_addend",
                    "slot.step_1_plus_sign",
                    "slot.step_1_second_addend",
                    "slot.step_1_line",
                    "slot.step_1_answer_ones",
                ),
            ),
            Region(
                id="region.arrow_1",
                role="connector",
                flow="absolute",
                slot_ids=(
                    "slot.arrow_1",
                ),
            ),
            Region(
                id="region.step_2",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.step_2_carry_hundreds",
                    "slot.step_2_carry_tens",
                    "slot.step_2_first_addend",
                    "slot.step_2_plus_sign",
                    "slot.step_2_second_addend",
                    "slot.step_2_line",
                    "slot.step_2_answer_tens",
                    "slot.step_2_answer_ones",
                ),
            ),
            Region(
                id="region.arrow_2",
                role="connector",
                flow="absolute",
                slot_ids=(
                    "slot.arrow_2",
                ),
            ),
            Region(
                id="region.step_3",
                role="question",
                flow="absolute",
                slot_ids=(
                    "slot.step_3_first_addend",
                    "slot.step_3_plus_sign",
                    "slot.step_3_second_addend",
                    "slot.step_3_line",
                    "slot.step_3_answer_thousands",
                    "slot.step_3_answer_hundreds",
                    "slot.step_3_answer_tens",
                    "slot.step_3_answer_ones",
                ),
            ),
        ),
        slots=(
            TextBoxSlot(
                id="slot.instruction",
                x=25,
                y=10,
                width=840,
                height=34,
                text="□ 안에 알맞은 수를 써넣으시오.",
                font_size=23,
                font_family="Noto Sans KR",
                fill="#202124",
                align="left",
                valign="middle",
            ),

            # 1단계: 일의 자리 계산
            TextBoxSlot(
                id="slot.step_1_carry_tens",
                x=87,
                y=42,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_1_first_addend",
                x=55,
                y=68,
                width=112,
                height=32,
                text="5 8 7",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_1_plus_sign",
                x=35,
                y=100,
                width=26,
                height=32,
                text="+",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_1_second_addend",
                x=55,
                y=100,
                width=112,
                height=32,
                text="6 4 9",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_1_line",
                x=38,
                y=127,
                width=132,
                height=18,
                text="────────",
                font_size=19,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_1_answer_ones",
                x=128,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),

            TextBoxSlot(
                id="slot.arrow_1",
                x=183,
                y=100,
                width=54,
                height=40,
                text="⇒",
                font_size=31,
                font_family="Noto Sans KR",
                fill="#333333",
                align="center",
                valign="middle",
            ),

            # 2단계: 십의 자리 계산
            TextBoxSlot(
                id="slot.step_2_carry_hundreds",
                x=275,
                y=42,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_carry_tens",
                x=309,
                y=42,
                width=28,
                height=28,
                text="□",
                font_size=27,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_first_addend",
                x=252,
                y=68,
                width=112,
                height=32,
                text="5 8 7",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_plus_sign",
                x=232,
                y=100,
                width=26,
                height=32,
                text="+",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_second_addend",
                x=252,
                y=100,
                width=112,
                height=32,
                text="6 4 9",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_line",
                x=235,
                y=127,
                width=132,
                height=18,
                text="────────",
                font_size=19,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_answer_tens",
                x=291,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_2_answer_ones",
                x=325,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),

            TextBoxSlot(
                id="slot.arrow_2",
                x=380,
                y=100,
                width=54,
                height=40,
                text="⇒",
                font_size=31,
                font_family="Noto Sans KR",
                fill="#333333",
                align="center",
                valign="middle",
            ),

            # 3단계: 백의 자리까지 계산하여 완성
            TextBoxSlot(
                id="slot.step_3_first_addend",
                x=470,
                y=68,
                width=112,
                height=32,
                text="5 8 7",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_plus_sign",
                x=450,
                y=100,
                width=26,
                height=32,
                text="+",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_second_addend",
                x=470,
                y=100,
                width=112,
                height=32,
                text="6 4 9",
                font_size=25,
                font_family="Noto Sans KR",
                fill="#202124",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_line",
                x=453,
                y=127,
                width=132,
                height=18,
                text="────────",
                font_size=19,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_answer_thousands",
                x=445,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_answer_hundreds",
                x=479,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_answer_tens",
                x=513,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
            TextBoxSlot(
                id="slot.step_3_answer_ones",
                x=547,
                y=146,
                width=34,
                height=38,
                text="□",
                font_size=34,
                font_family="Noto Sans KR",
                fill="#111111",
                align="center",
                valign="middle",
            ),
        ),
    )


PROBLEM_TEMPLATE = build_problem_template()


SEMANTIC = {
    "problem_id": PROBLEM_ID,
    "problem_type": "stepwise_vertical_addition_fill_blanks",
    "metadata": {
        "grade": 3,
        "semester": 1,
        "subject": "수학",
        "topic": "받아올림이 있는 세 자리 수의 덧셈",
        "language": "ko-KR",
    },
    "domain": {
        "objects": [
            {
                "id": "addition.main",
                "type": "vertical_addition",
                "label": "587과 649의 덧셈",
                "first_addend": 587,
                "second_addend": 649,
                "sum": 1236,
            },
            {
                "id": "carry.ones_to_tens",
                "type": "carry",
                "label": "일의 자리에서 십의 자리로 받아올림",
                "from_place": "ones",
                "to_place": "tens",
                "value": 1,
            },
            {
                "id": "carry.tens_to_hundreds",
                "type": "carry",
                "label": "십의 자리에서 백의 자리로 받아올림",
                "from_place": "tens",
                "to_place": "hundreds",
                "value": 1,
            },
        ],
        "relations": [
            {
                "id": "relation.main_sum",
                "type": "sum_of",
                "subject": "addition.main",
                "values": [587, 649],
            },
        ],
    },
    "answer": {
        "value": [
            1,
            6,
            1,
            1,
            3,
            6,
            1,
            2,
            3,
            6,
        ],
        "unit": "",
        "items": [
            {"id": "answer.step_1.carry_tens", "value": 1},
            {"id": "answer.step_1.ones", "value": 6},
            {"id": "answer.step_2.carry_hundreds", "value": 1},
            {"id": "answer.step_2.carry_tens", "value": 1},
            {"id": "answer.step_2.tens", "value": 3},
            {"id": "answer.step_2.ones", "value": 6},
            {"id": "answer.step_3.thousands", "value": 1},
            {"id": "answer.step_3.hundreds", "value": 2},
            {"id": "answer.step_3.tens", "value": 3},
            {"id": "answer.step_3.ones", "value": 6},
        ],
    },
}

SEMANTIC_OVERRIDE = SEMANTIC


SOLVABLE = {'schema': 'modu.solvable.v1.2',
 'problem_id': 'P3_1_01_00040_02153',
 'problem_type': 'stepwise_vertical_addition_fill_blanks',
 'inputs': {'target_label': '받아올림한 수와 각 단계의 계산 결과',
            'unit': '',
            'answer_type': 'digit_list',
            'quantities': {'first_addend': 587, 'second_addend': 649},
            'conditions': ['일의 자리부터 차례대로 계산합니다.',
                           '각 자리의 합이 10 이상이면 바로 윗자리로 1을 받아올림합니다.',
                           '각 단계에서 새로 구한 받아올림 수와 계산 결과를 네모 안에 씁니다.']},
 'given': [{'ref': 'addition.main', 'value': {'first_addend': 587, 'second_addend': 649}}],
 'target': {'ref': 'answer.stepwise_vertical_addition_blanks', 'type': 'digit_list'},
 'method': '일의 자리, 십의 자리, 백의 자리 순서로 더하고 각 단계의 받아올림을 다음 자리 계산에 포함한다.',
 'plan': ['7과 9를 더하여 일의 자리 수와 받아올림 수를 구한다.',
          '8과 4에 받아올림한 1을 더하여 십의 자리 수와 받아올림 수를 구한다.',
          '5와 6에 받아올림한 1을 더하여 최종 합을 완성한다.'],
 'steps': [{'id': 'step.add_ones',
            'expr': '7 + 9',
            'value': 16,
            'explanation': '일의 자리에서 7과 9를 더하면 16이므로 6을 쓰고 십의 자리로 1을 받아올림합니다.'},
           {'id': 'step.add_tens',
            'expr': '8 + 4 + 1',
            'value': 13,
            'explanation': '십의 자리에서 8과 4에 받아올림한 1을 더하면 13이므로 3을 쓰고 백의 자리로 1을 받아올림합니다.'},
           {'id': 'step.add_hundreds',
            'expr': '5 + 6 + 1',
            'value': 12,
            'explanation': '백의 자리에서 5와 6에 받아올림한 1을 더하면 12이므로 백의 자리에 2, 천의 자리에 1을 씁니다.'},
           {'id': 'step.compose_sum',
            'expr': '587 + 649',
            'value': 1236,
            'explanation': '따라서 587과 649의 합은 1236입니다.'}],
 'checks': [{'id': 'check.ones', 'expr': '7 + 9', 'expected': 16, 'actual': 16, 'pass': True},
            {'id': 'check.tens', 'expr': '8 + 4 + 1', 'expected': 13, 'actual': 13, 'pass': True},
            {'id': 'check.hundreds',
             'expr': '5 + 6 + 1',
             'expected': 12,
             'actual': 12,
             'pass': True},
            {'id': 'check.total',
             'expr': '587 + 649',
             'expected': 1236,
             'actual': 1236,
             'pass': True},
            {'id': 'check.inverse',
             'expr': '1236 - 649',
             'expected': 587,
             'actual': 587,
             'pass': True}],
 'answer': {'value': [1, 6, 1, 1, 3, 6, 1, 2, 3, 6],
            'unit': '',
            'items': [{'id': 'answer.step_1.carry_tens', 'value': 1},
                      {'id': 'answer.step_1.ones', 'value': 6},
                      {'id': 'answer.step_2.carry_hundreds', 'value': 1},
                      {'id': 'answer.step_2.carry_tens', 'value': 1},
                      {'id': 'answer.step_2.tens', 'value': 3},
                      {'id': 'answer.step_2.ones', 'value': 6},
                      {'id': 'answer.step_3.thousands', 'value': 1},
                      {'id': 'answer.step_3.hundreds', 'value': 2},
                      {'id': 'answer.step_3.tens', 'value': 3},
                      {'id': 'answer.step_3.ones', 'value': 6}]},
 'understanding': {'summary': 'Find 받아올림한 수와 각 단계의 계산 결과 using the given information.',
                   'facts': [{'ref': 'addition.main',
                              'label': 'main',
                              'value': {'first_addend': 587, 'second_addend': 649},
                              'unit': '',
                              'source': 'explicit'}],
                   'unknowns': [{'ref': 'answer.stepwise_vertical_addition_blanks',
                                 'label': '받아올림한 수와 각 단계의 계산 결과',
                                 'unit': '',
                                 'source': 'unknown'}],
                   'relation': {'type': '일의 자리, 십의 자리, 백의 자리 순서로 더하고 각 단계의 받아올림을 다음 자리 계산에 포함한다.',
                                'statement': '7과 9를 더하여 일의 자리 수와 받아올림 수를 구한다.',
                                'symbolic': '7 + 9',
                                'uses': ['addition.main'],
                                'result': 'answer.stepwise_vertical_addition_blanks'},
                   'diagnostic_questions': [{'id': 'understand.target',
                                             'type': 'multiple_choice',
                                             'prompt': 'What should we find?',
                                             'choices': ['main', '받아올림한 수와 각 단계의 계산 결과'],
                                             'answer_index': 1}]}}

SEMANTIC_ANSWER = SOLVABLE["answer"]
