from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008705",
        title="규칙에 따라 원을 그린 그림",
        canvas=Canvas(width=940, height=620, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.header",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.qtext1",
                    "slot.qtext2",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.v9",
                    "slot.graphpaper.v10",
                    "slot.graphpaper.v11",
                    "slot.graphpaper.v12",
                    "slot.graphpaper.v13",
                    "slot.graphpaper.v14",
                    "slot.graphpaper.v15",
                    "slot.graphpaper.v16",
                    "slot.graphpaper.v17",
                    "slot.graphpaper.v18",
                    "slot.graphpaper.v19",
                    "slot.graphpaper.v20",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                    "slot.qtext2.copy14.copy15",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle2",
                    "slot.center1",
                    "slot.center2",
                    "slot.center3",
                    "slot.center4",
                    "slot.circle2.copy11",
                    "slot.circle2.copy11.copy12",
                    "slot.circle2.copy11.copy12.copy13",
                ),
            ),
            Region(
                id="region.bubble",
                role="explanation",
                flow="absolute",
                slot_ids=("slot.bubble", "slot.qtext2.copy14", "slot.qtext2.copy16"),
            ),
            Region(id="region.choice", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.qtext1",
                prompt="",
                text="규칙에 따라 원을 그린 그림입니다. 그린 규칙을 바르게 설명했으면 ○표,",
                style_role="question",
                x=31,
                y=75,
                font_size=30,
            ),
            TextSlot(
                id="slot.qtext2",
                prompt="",
                text="그렇지 않으면 ×표를 선택하세요.",
                style_role="question",
                x=30,
                y=125,
                font_size=30,
            ),
            CircleSlot(
                id="slot.circle2",
                prompt="",
                cx=263,
                cy=280,
                r=83,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(id="slot.center1", prompt="", cx=261, cy=280, r=5, fill="#ff4aa2"),
            CircleSlot(id="slot.center2", prompt="", cx=375, cy=280, r=5, fill="#ff4aa2"),
            CircleSlot(id="slot.center3", prompt="", cx=485, cy=280, r=5, fill="#ff4aa2"),
            CircleSlot(id="slot.center4", prompt="", cx=600, cy=280, r=5, fill="#ff4aa2"),
            RectSlot(
                id="slot.bubble", prompt="", x=121, y=435, width=635, height=105, fill="#d9effb"
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=150,
                y1=170,
                x2=150,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=178,
                y1=170,
                x2=178,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=206,
                y1=170,
                x2=206,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=234,
                y1=170,
                x2=234,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=262,
                y1=170,
                x2=262,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=290,
                y1=170,
                x2=290,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=318,
                y1=170,
                x2=318,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=346,
                y1=170,
                x2=346,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=374,
                y1=170,
                x2=374,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v9",
                prompt="",
                x1=402,
                y1=170,
                x2=402,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v10",
                prompt="",
                x1=430,
                y1=170,
                x2=430,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v11",
                prompt="",
                x1=458,
                y1=170,
                x2=458,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v12",
                prompt="",
                x1=486,
                y1=170,
                x2=486,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v13",
                prompt="",
                x1=514,
                y1=170,
                x2=514,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v14",
                prompt="",
                x1=542,
                y1=170,
                x2=542,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v15",
                prompt="",
                x1=570,
                y1=170,
                x2=570,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v16",
                prompt="",
                x1=598,
                y1=170,
                x2=598,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v17",
                prompt="",
                x1=626,
                y1=170,
                x2=626,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v18",
                prompt="",
                x1=654,
                y1=170,
                x2=654,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v19",
                prompt="",
                x1=682,
                y1=170,
                x2=682,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v20",
                prompt="",
                x1=710,
                y1=170,
                x2=710,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=150,
                y1=170,
                x2=710,
                y2=170,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=150,
                y1=198,
                x2=710,
                y2=198,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=150,
                y1=226,
                x2=710,
                y2=226,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=150,
                y1=254,
                x2=710,
                y2=254,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=150,
                y1=282,
                x2=710,
                y2=282,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=150,
                y1=310,
                x2=710,
                y2=310,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=150,
                y1=338,
                x2=710,
                y2=338,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=150,
                y1=366,
                x2=710,
                y2=366,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=150,
                y1=394,
                x2=710,
                y2=394,
                stroke="#2563eb",
                stroke_width=1,
            ),
            CircleSlot(
                id="slot.circle2.copy11",
                prompt="",
                cx=375,
                cy=280,
                r=85,
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle2.copy11.copy12",
                prompt="",
                cx=485,
                cy=280,
                r=85,
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.circle2.copy11.copy12.copy13",
                prompt="",
                cx=600,
                cy=280,
                r=85,
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.qtext2.copy14",
                prompt="",
                text="원의 중심이 오른쪽으로 모눈 4칸씩 옮겨가고",
                x=161,
                y=475,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.qtext2.copy14.copy15",
                prompt="",
                text="원의 중심이 오른쪽으로 모눈 4칸씩 옮겨가고",
                x=305,
                y=700,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.qtext2.copy16",
                prompt="",
                text="원의 반지름이 모눈 3칸씩 늘어나게 그렸어.",
                x=166,
                y=520,
                font_size=30,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008705",
    "problem_type": "참거짓판단",
    "metadata": {
        "language": "ko",
        "question": "규칙에 따라 원을 그린 그림에서 규칙 설명이 맞는지 판단하는 문제",
        "instruction": "그린 규칙을 바르게 설명했으면 ○표, 그렇지 않으면 ×표를 선택하기",
    },
    "domain": {
        "objects": [
            {"id": "obj.diagram.circles", "type": "circle_sequence", "count": 4},
            {"id": "obj.rule.statement", "type": "rule_description"},
            {"id": "obj.answer.mark", "type": "choice_mark", "value": "×"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.diagram.circles", "obj.rule.statement"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.compare_rule_to_picture"],
            },
            "plan": {
                "method": "visual_consistency_check",
                "description": "그림의 반복 규칙과 말풍선의 설명이 서로 같은지 확인한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_center_shift_rule",
                    "compare_radius_rule",
                    "decide_true_false",
                ]
            },
            "review": {"check_methods": ["statement_picture_match_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "true_false_choice",
            "description": "그린 규칙이 바르게 설명되었는지에 대한 선택",
        },
        "value": 0,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008705",
    "problem_type": "참거짓판단",
    "inputs": {
        "total_ticks": 0,
        "target_label": "선택",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.diagram.circles", "value": {"count": 4}},
        {
            "ref": "obj.rule.statement",
            "value": {
                "text": "원의 중심이 오른쪽으로 모눈 4칸씩 옮겨 가고 원의 반지름이 모눈 3칸씩 늘어나게 그렸어."
            },
        },
    ],
    "target": {"ref": "answer.target", "type": "true_false_choice"},
    "method": "visual_consistency_check",
    "plan": [
        "그림의 원 배열과 말풍선의 규칙 설명을 비교한다.",
        "중심 이동 규칙과 반지름 변화 규칙이 그림과 일치하는지 확인한다.",
        "일치 여부에 따라 ○ 또는 ×를 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "그림의 원 4개와 말풍선의 규칙 설명을 비교한다.", "value": "비교"},
        {
            "id": "step.2",
            "expr": "중심 이동 규칙과 반지름 변화 규칙의 일치 여부를 확인한다.",
            "value": "확인",
        },
        {"id": "step.3", "expr": "선택 결과를 판단한다.", "value": "×"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "그림 설명과 말풍선 설명이 일치하는가",
            "expected": False,
            "actual": False,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "인쇄된 정답 표기 확인",
            "expected": "×",
            "actual": "×",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "true_false_choice",
            "description": "그린 규칙이 바르게 설명되었는지에 대한 선택",
        },
        "value": 0,
        "unit": "",
    },
}
