from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    PathSlot,
    PolygonSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
    ImageSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008684",
        title="누름 못과 띠 종이로 원 그리기",
        canvas=Canvas(width=939.0, height=593.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.stem",),
            ),
            Region(
                id="region.diagram.left",
                role="instruction_diagram_left",
                flow="absolute",
                slot_ids=(
                    "slot.left.frame",
                    "slot.left.circle",
                    "slot.inserted.rect.2",
                    "slot.left.arrow.1",
                    "slot.left.dot.1",
                    "slot.left.dot.2",
                    "slot.left.dot.3",
                    "slot.left.dot.4",
                    "slot.left.text",
                ),
            ),
            Region(
                id="region.diagram.right",
                role="instruction_diagram_right",
                flow="absolute",
                slot_ids=(
                    "slot.right.frame",
                    "slot.right.circle",
                    "slot.right.dash.v",
                    "slot.right.dash.h",
                    "slot.right.center",
                    "slot.right.dot.top",
                    "slot.right.dot.bottom",
                    "slot.right.dot.left",
                    "slot.right.dot.right",
                    "slot.right.text",
                    "slot.right.center.copy4",
                ),
            ),
            Region(
                id="region.choice",
                role="choice_statement",
                flow="absolute",
                slot_ids=("slot.choice.frame", "slot.choice.text"),
            ),
            Region(
                id="region.answer",
                role="answer_explanation",
                flow="absolute",
                slot_ids=(),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.stem",
                prompt="",
                text="누름 못과 띠 종이를 이용하여 원을 그렸습니다. 그림을 보고 알맞은 말을 선택하세요.    ",
                style_role="question",
                x=10,
                y=45,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.left.frame",
                prompt="",
                x=115,
                y=130,
                width=225,
                height=215,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.left.circle",
                prompt="",
                cx=230,
                cy=235,
                r=105,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            RectSlot(
                id="slot.inserted.rect.2",
                prompt="",
                x=204,
                y=224,
                width=185,
                height=30,
                fill="#bfdbfe",
                stroke="#111827",
                stroke_width=1.5,
                transform="rotate(-34 223 239)",
            ),
            PathSlot(
                id="slot.left.arrow.1",
                prompt="",
                d="M 215 310 C 115 290 55 295 30 330",
                stroke="#111111",
                stroke_width=2,
                transform="rotate(-35 130 295.43)",
                fill="none",
            ),
            CircleSlot(
                id="slot.left.dot.1",
                prompt="",
                cx=262,
                cy=211,
                r=4,
                fill="#6BB7FF",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.left.dot.2",
                prompt="",
                cx=293,
                cy=191,
                r=4,
                fill="#6BB7FF",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.left.dot.3",
                prompt="",
                cx=320,
                cy=173,
                r=4,
                fill="#6BB7FF",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.left.dot.4",
                prompt="",
                cx=345,
                cy=156,
                r=4,
                fill="#6BB7FF",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.left.text",
                prompt="",
                text="① 한쪽 구멍에 누름 못을 꽂아 띠 종이를 고정해요.",
                style_role="annotation",
                x=45,
                y=420,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.right.frame",
                prompt="",
                x=626,
                y=121,
                width=227,
                height=214,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.right.circle",
                prompt="",
                cx=739,
                cy=229,
                r=108,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.right.dash.v",
                prompt="",
                x1=739,
                y1=121,
                x2=739,
                y2=335,
                stroke_dasharray="5 3",
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.right.dash.h",
                prompt="",
                x1=626,
                y1=229,
                x2=853,
                y2=229,
                stroke_dasharray="5 3",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.right.center",
                prompt="",
                cx=739,
                cy=229,
                r=5,
                fill="#B0B0B0",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.right.dot.top",
                prompt="",
                cx=739,
                cy=121,
                r=4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.right.dot.bottom",
                prompt="",
                cx=739,
                cy=335,
                r=4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.right.dot.left",
                prompt="",
                cx=626,
                cy=229,
                r=4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.right.dot.right",
                prompt="",
                cx=853,
                cy=229,
                r=4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.right.text",
                prompt="",
                text="② 다른 구멍에 연필을 꽂고 한 바퀴 돌려    원을 그려요.  ",
                style_role="annotation",
                x=45,
                y=470,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.choice.frame",
                prompt="",
                x=25,
                y=500,
                width=830,
                height=85,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.choice.text",
                prompt="",
                text="누름 못이 꽂힌 점에서 원 위에 찍은 4개의 점까지의 길이는 모두 (같습니다, 다릅니다).",
                style_role="question",
                x=40.002,
                y=534.014,
                font_size=30,
                fill="#111111",
            ),
            CircleSlot(
                id="slot.right.center.copy4",
                prompt="",
                cx=227,
                cy=237,
                r=8,
                fill="#B0B0B0",
                stroke="#111111",
                stroke_width=2,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()
SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008684",
    "problem_type": "circle_radius_relation",
    "metadata": {
        "language": "ko",
        "question": "누름 못과 띠 종이로 그린 원에서 원 위의 점들과 중심 사이의 거리 관계를 묻는 문제",
        "instruction": "알맞은 말을 선택한다.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.center",
                "type": "point",
                "role": "center",
                "description": "누름 못이 꽂힌 점",
            },
            {
                "id": "obj.points_on_circle",
                "type": "set_of_points",
                "role": "points_on_circle",
                "description": "원 위에 찍은 4개의 점",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.center", "obj.points_on_circle"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.equal_distance"],
            },
            "plan": {
                "method": "circle_property",
                "description": "원의 중심에서 원 위의 점까지의 거리는 모두 같다는 성질을 확인한다.",
            },
            "execute": {"expected_operations": ["compare_distances_from_center"]},
            "review": {"check_methods": ["circle_radius_consistency"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_word",
            "description": "누름 못이 꽂힌 점에서 원 위에 찍은 4개의 점까지의 길이 관계",
        },
        "value": "같습니다",
        "unit": "",
    },
}
SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008684",
    "problem_type": "circle_radius_relation",
    "inputs": {
        "total_ticks": 4,
        "target_label": "같습니다, 다릅니다",
        "target_ticks": 4,
        "target_count": 4,
        "unit": "",
    },
    "given": [
        {"ref": "obj.center", "value": {"role": "center", "description": "누름 못이 꽂힌 점"}},
        {
            "ref": "obj.points_on_circle",
            "value": {"count": 4, "description": "원 위에 찍은 4개의 점"},
        },
    ],
    "target": {"ref": "answer.target", "type": "choice_word"},
    "method": "circle_property",
    "plan": [
        "원의 중심에서 원 위의 점까지의 거리가 모두 같은지 확인한다.",
        "보기 중 알맞은 말을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "원 위의 각 점은 중심에서 같은 반지름만큼 떨어져 있다.",
            "value": "같다",
        },
        {"id": "step.2", "expr": "4개의 점에 대한 거리 관계를 비교한다.", "value": "같습니다"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "중심에서 각 점까지의 거리가 동일한가",
            "expected": "같다",
            "actual": "같다",
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "선택어가 보기와 일치하는가",
            "expected": "같습니다",
            "actual": "같습니다",
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_word",
            "description": "누름 못이 꽂힌 점에서 원 위에 찍은 4개의 점까지의 길이 관계",
        },
        "value": "같습니다",
        "unit": "",
    },
}
