from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008702",
        title="원의 지름과 중심",
        canvas=Canvas(width=896.0, height=480.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.v9",
                    "slot.graphpaper.v10",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle",
                    "slot.pt.g",
                    "slot.pt.n",
                    "slot.pt.d",
                    "slot.pt.r",
                    "slot.lb.g",
                    "slot.lb.n",
                    "slot.lb.d",
                    "slot.lb.r",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
            Region(id="region.explain", role="explanation", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="원에 지름을 그을 때 반드시 지나는 점을 찾아 선택해 보세요.  ",
                style_role="question",
                x=18.0,
                y=44.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2", prompt="", text="", style_role="question", x=0.0, y=0.0, font_size=28
            ),
            CircleSlot(id="slot.circle", prompt="", cx=355, cy=245, r=130, fill="none"),
            CircleSlot(id="slot.pt.g", prompt="", cx=270, cy=200, r=5, fill="#d94b89"),
            CircleSlot(id="slot.pt.n", prompt="", cx=355, cy=241, r=5, fill="#d94b89"),
            CircleSlot(id="slot.pt.d", prompt="", cx=355, cy=375, r=5, fill="#d94b89"),
            CircleSlot(id="slot.pt.r", prompt="", cx=447, cy=241, r=5, fill="#d94b89"),
            TextSlot(
                id="slot.lb.g", prompt="", text="ㄱ", style_role="label", x=275, y=200, font_size=20
            ),
            TextSlot(
                id="slot.lb.n", prompt="", text="ㄴ", style_role="label", x=360, y=265, font_size=20
            ),
            TextSlot(
                id="slot.lb.d", prompt="", text="ㄷ", style_role="label", x=360, y=395, font_size=20
            ),
            TextSlot(
                id="slot.lb.r", prompt="", text="ㄹ", style_role="label", x=450, y=265, font_size=20
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=140,
                y1=70,
                x2=140,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=185,
                y1=70,
                x2=185,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=225,
                y1=70,
                x2=225,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=270,
                y1=70,
                x2=270,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=310,
                y1=70,
                x2=310,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=355,
                y1=70,
                x2=355,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=405,
                y1=70,
                x2=405,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=445,
                y1=70,
                x2=445,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=485,
                y1=70,
                x2=485,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v9",
                prompt="",
                x1=525,
                y1=70,
                x2=525,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v10",
                prompt="",
                x1=570,
                y1=70,
                x2=570,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=140,
                y1=70,
                x2=570,
                y2=70,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=140,
                y1=115,
                x2=570,
                y2=115,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=140,
                y1=155,
                x2=570,
                y2=155,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=140,
                y1=200,
                x2=570,
                y2=200,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=140,
                y1=240,
                x2=570,
                y2=240,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=140,
                y1=290,
                x2=570,
                y2=290,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=140,
                y1=330,
                x2=570,
                y2=330,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=140,
                y1=375,
                x2=570,
                y2=375,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=140,
                y1=420,
                x2=570,
                y2=420,
                stroke="#2563eb",
                stroke_width=1,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008702",
    "problem_type": "geometry_circle_center",
    "metadata": {
        "language": "ko",
        "question": "원에 지름을 그을 때 반드시 지나는 점을 찾아 선택해 보세요.",
        "instruction": "원의 지름이 반드시 지나는 점을 고른다.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.point.g", "type": "point", "label": "ㄱ"},
            {"id": "obj.point.n", "type": "point", "label": "ㄴ"},
            {"id": "obj.point.d", "type": "point", "label": "ㄷ"},
            {"id": "obj.point.r", "type": "point", "label": "ㄹ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.point.g",
                    "obj.point.n",
                    "obj.point.d",
                    "obj.point.r",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.diameter_passes_center"],
            },
            "plan": {
                "method": "circle_center_identification",
                "description": "원의 중심을 나타내는 점을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "identify_center_like_point",
                    "match_with_diameter_property",
                ]
            },
            "review": {"check_methods": ["property_check_diameter_through_center"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_point", "description": "원에 지름을 그을 때 반드시 지나는 점"},
        "value": "ㄴ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008702",
    "problem_type": "geometry_circle_center",
    "inputs": {
        "total_ticks": 0,
        "target_label": "ㄴ",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {"ref": "obj.point.g", "value": {"label": "ㄱ"}},
        {"ref": "obj.point.n", "value": {"label": "ㄴ"}},
        {"ref": "obj.point.d", "value": {"label": "ㄷ"}},
        {"ref": "obj.point.r", "value": {"label": "ㄹ"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_point"},
    "method": "circle_center_identification",
    "plan": ["원의 지름은 반드시 원의 중심을 지난다.", "중심처럼 보이는 점을 찾는다."],
    "steps": [
        {"id": "step.1", "expr": "원의 지름은 원의 중심을 지난다", "value": "property"},
        {"id": "step.2", "expr": "중심에 해당하는 점을 선택한다", "value": "ㄴ"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "선택한 점이 원의 중심과 일치하는가",
            "expected": "ㄴ",
            "actual": "ㄴ",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_point", "description": "원에 지름을 그을 때 반드시 지나는 점"},
        "value": "ㄴ",
        "unit": "",
    },
}
