from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, LineSlot, CircleSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008695",
        title="원을 둘로 똑같이 나누는 선분",
        canvas=Canvas(width=950.0, height=560.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.title",
                    "slot.fig1.v",
                    "slot.fig2.v",
                    "slot.fig2.h",
                    "slot.fig3.v",
                    "slot.fig3.h",
                    "slot.fig3.center",
                    "slot.arrow1",
                    "slot.arrow2",
                    "slot.desc1.1",
                    "slot.desc1.2",
                    "slot.desc1.3",
                    "slot.desc1.4",
                    "slot.desc2.1",
                    "slot.desc2.2",
                    "slot.desc2.3",
                    "slot.desc2.4",
                    "slot.desc3.1",
                    "slot.desc3.2",
                    "slot.desc3.3",
                    "slot.desc3.4",
                ),
            ),
            Region(
                id="region.item1",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.item1.q",
                    "slot.item1.arrow",
                    "slot.item1.q.copy3",
                    "slot.item1.q.copy3.copy1",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.title",
                prompt="",
                text="원을 둘로 똑같이 나누는 선분을 알아보려고 합니다. 알맞은말을 선택하세요.",
                style_role="question",
                x=20,
                y=30,
                font_size=30,
            ),
            CircleSlot(
                id="slot.fig1.circle", prompt="", cx=180.0, cy=136.0, r=56.0, fill="#ffeef2"
            ),
            LineSlot(
                id="slot.fig1.v",
                prompt="",
                x1=180.0,
                y1=84.0,
                x2=180.0,
                y2=188.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(
                id="slot.fig2.circle", prompt="", cx=443.0, cy=136.0, r=56.0, fill="#ffeef2"
            ),
            LineSlot(
                id="slot.fig2.v",
                prompt="",
                x1=443.0,
                y1=84.0,
                x2=443.0,
                y2=188.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            LineSlot(
                id="slot.fig2.h",
                prompt="",
                x1=391.0,
                y1=136.0,
                x2=495.0,
                y2=136.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(id="slot.fig3.circle", prompt="", cx=745, cy=135, r=55, fill="#ffeef2"),
            LineSlot(
                id="slot.fig3.v",
                prompt="",
                x1=745,
                y1=85,
                x2=745,
                y2=190,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            LineSlot(
                id="slot.fig3.h",
                prompt="",
                x1=690,
                y1=135,
                x2=800,
                y2=135,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(id="slot.fig3.center", prompt="", cx=746, cy=135, r=5, fill="#ff5b8d"),
            TextSlot(
                id="slot.arrow1",
                prompt="",
                text="→",
                style_role="body",
                x=318.0,
                y=144.0,
                font_size=34,
            ),
            TextSlot(
                id="slot.arrow2",
                prompt="",
                text="→",
                style_role="body",
                x=586.0,
                y=144.0,
                font_size=34,
            ),
            TextSlot(
                id="slot.desc1.1",
                prompt="",
                text="원 모양의 종이를",
                style_role="body",
                x=90,
                y=236,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.2",
                prompt="",
                text="둘로 똑같이 나누어",
                style_role="body",
                x=90,
                y=274,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.3",
                prompt="",
                text="지도록 접었다가 펼",
                style_role="body",
                x=90,
                y=312,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.4",
                prompt="",
                text="칩니다.",
                style_role="body",
                x=90,
                y=350,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.1",
                prompt="",
                text="다른 방향으로도 둘",
                style_role="body",
                x=350,
                y=235,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.2",
                prompt="",
                text="로 똑같이 나누어지",
                style_role="body",
                x=350,
                y=271,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.3",
                prompt="",
                text="도록 접었다가 펼칩",
                style_role="body",
                x=350,
                y=310,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.4",
                prompt="",
                text="니다.",
                style_role="body",
                x=350,
                y=350,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.1",
                prompt="",
                text="접었을 때 생기는 선",
                style_role="body",
                x=620,
                y=234,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.2",
                prompt="",
                text="분들이 만나는 점을",
                style_role="body",
                x=620,
                y=274,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.3",
                prompt="",
                text="점 ㅇ이라고 표시합",
                style_role="body",
                x=620,
                y=309,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.4",
                prompt="",
                text="니다.",
                style_role="body",
                x=620,
                y=349,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.q",
                prompt="",
                text="(1) 점 ㅇ에서 원 위의 한 점까지의 길이는 모두(같습니다, 다릅니다 ).",
                style_role="question",
                x=90,
                y=455,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.arrow",
                prompt="",
                text="→",
                style_role="body",
                x=95,
                y=494,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.q.copy3",
                prompt="",
                text="점 ㅇ는 원의 중심입니다.",
                x=127,
                y=498,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.q.copy3.copy1",
                prompt="",
                text="ㅇ",
                x=750,
                y=135,
                font_size=20,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008695",
    "problem_type": "도형_원의중심",
    "metadata": {
        "language": "ko",
        "question": "원을 둘로 똑같이 나누는 선분을 알아보려고 합니다. 알맞은 말을 선택하세요.",
        "instruction": "점 ○에서 원 위의 한 점까지의 길이에 관한 알맞은 말을 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center_mark", "type": "point_mark", "label": "○"},
            {"id": "obj.fold_lines", "type": "fold_lines", "count": 3},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.center_mark", "obj.fold_lines"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.equal_radius"],
            },
            "plan": {
                "method": "center_property_check",
                "description": "중심에서 원 위의 점까지의 길이가 모두 같은지 확인하는 문장 구조를 읽는다.",
            },
            "execute": {"expected_operations": ["문장 선택지 확인", "원의 중심 성질 연결"]},
            "review": {"check_methods": ["문장 의미가 중심의 성질과 일치하는지 확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_sentence",
            "description": "점 ○에서 원 위의 한 점까지의 길이에 대한 알맞은 말",
        },
        "value": 1,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008695",
    "problem_type": "도형_원의중심",
    "inputs": {
        "total_ticks": 0,
        "target_label": "알맞은 말",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {"ref": "obj.center_mark", "value": {"label": "○"}},
        {"ref": "obj.fold_lines", "value": {"count": 3}},
    ],
    "target": {"ref": "answer.target", "type": "choice_sentence"},
    "method": "center_property_check",
    "plan": [
        "그림에서 접은 선들이 만나는 점과 원의 중심 성질을 연결한다.",
        "문장 선택지 중 중심의 성질과 맞는 말을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "점 ○에서 원 위의 한 점까지의 길이의 성질을 확인한다.",
            "value": "같은 길이",
        },
        {"id": "step.2", "expr": "중심의 성질에 맞는 선택을 고른다.", "value": "같습니다"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "점 ○이 원의 중심이면 원 위의 모든 점까지의 길이는 같다.",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_sentence",
            "description": "점 ○에서 원 위의 한 점까지의 길이에 대한 알맞은 말",
        },
        "value": 1,
        "unit": "",
    },
}
