from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    CircleSlot,
    LineSlot,
    ProblemTemplate,
    RectSlot,
    Region,
    TextSlot,
    compass_on_ruler_slots,
)


def build_problem_template() -> ProblemTemplate:
    step_d = compass_on_ruler_slots(
        "slot.step.d",
        x=(565.0) + (-5.0),
        y=(154.0) + (45.0),
        unit_width=48.0,
        needle_mark=0.0,
        pencil_mark=1.0,
        hinge_offset_x=10.0,
        hinge_y_offset=-82.0,
        scale=0.72,
    )
    return ProblemTemplate(
        id="S3_초등_3_008713",
        title="반지름이 1 cm인 원을 그리는 순서",
        canvas=Canvas(width=960.0, height=420.0, coordinate_mode="logical"),
        regions=(
            Region(id="region.stem", role="stem", flow="absolute", slot_ids=("slot.stem",)),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.box",
                    "slot.circle.main",
                    "slot.dot.center",
                    "slot.dot.inner",
                    "slot.point.mid",
                    "slot.ring.mid",
                    "slot.option.1",
                    "slot.option.2",
                    "slot.option.3",
                    "slot.option.4",
                    "slot.option.5",
                    "slot.option.1.copy1",
                    "slot.option.1.copy2",
                    "slot.option.1.copy3",
                    *(slot.id for slot in step_d),
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.stem",
                prompt="",
                text="반지름이 1 cm인 원을 그리는 순서를 바르게 나타낸 것을 고르세요.",
                style_role="question",
                x=15,
                y=35,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.box",
                prompt="",
                x=30,
                y=60,
                width=720,
                height=220,
                fill="#ffffff",
                stroke="#111111",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.circle.main",
                prompt="",
                cx=190,
                cy=182,
                r=48,
                fill="#FFFFFF",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.dot.center",
                prompt="",
                cx=190,
                cy=182,
                r=2.4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.dot.inner",
                prompt="",
                cx=174.11114501953125,
                cy=190,
                r=5,
                fill="#FFFFFF",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.point.mid",
                prompt="",
                cx=387,
                cy=166,
                r=2.4,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.ring.mid",
                prompt="",
                cx=382,
                cy=179,
                r=4.5,
                fill="#FFFFFF",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.option.1",
                prompt="",
                text="ㄱ",
                style_role="answer_choice",
                x=65,
                y=105,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.2",
                prompt="",
                text="② ㄴ, ㄷ, ㄱ",
                style_role="answer_choice",
                x=280,
                y=335,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.3",
                prompt="",
                text="③ ㄷ, ㄱ, ㄴ",
                style_role="answer_choice",
                x=525,
                y=335,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.4",
                prompt="",
                text="④ ㄱ, ㄷ, ㄴ",
                style_role="answer_choice",
                x=25,
                y=375,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.5",
                prompt="",
                text="⑤ ㄴ, ㄱ, ㄷ",
                style_role="answer_choice",
                x=280,
                y=375,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.1.copy1",
                prompt="",
                text="① ㄱ, ㄴ, ㄷ",
                x=25,
                y=332,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.1.copy2",
                prompt="",
                text="ㄴ",
                x=300,
                y=110,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.option.1.copy3",
                prompt="",
                text="ㄷ",
                x=495,
                y=115,
                font_size=30,
                fill="#111111",
            ),
            *step_d,
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008713",
    "problem_type": "sequence_ordering",
    "metadata": {
        "language": "ko",
        "question": "반지름이 1 cm인 원을 그리는 순서를 바르게 나타낸 것을 고르세요.",
        "instruction": "그림의 순서를 바르게 고르기",
        "points": 0,
    },
    "domain": {
        "objects": [
            {"id": "obj.step.g1", "type": "procedure_step", "name": "ㄱ"},
            {"id": "obj.step.g2", "type": "procedure_step", "name": "ㄴ"},
            {"id": "obj.step.g3", "type": "procedure_step", "name": "ㄷ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.step.g1", "obj.step.g2", "obj.step.g3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.order"],
            },
            "plan": {
                "method": "sequence_matching",
                "description": "그림과 해설을 보고 올바른 순서를 찾는다.",
            },
            "execute": {"expected_operations": ["identify_steps", "match_order", "select_choice"]},
            "review": {"check_methods": ["compare_with_explanation", "verify_choice_label"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "choice_number", "description": "원 그리기 순서의 정답 선택지"},
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008713",
    "problem_type": "sequence_ordering",
    "inputs": {
        "total_ticks": 3,
        "target_label": "정답 선택지",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.step.g1", "value": "ㄱ"},
        {"ref": "obj.step.g2", "value": "ㄴ"},
        {"ref": "obj.step.g3", "value": "ㄷ"},
    ],
    "target": {"ref": "answer.target", "type": "choice_number"},
    "method": "sequence_matching",
    "plan": [
        "해설의 순서를 따라 올바른 단계 배열을 확인한다.",
        "해당 순서와 같은 선택지를 찾는다.",
    ],
    "steps": [{"id": "step.1", "expr": "ㄴ → ㄷ → ㄱ", "value": 2}],
    "checks": [
        {"id": "check.1", "expr": "선택지 ② = ㄴ, ㄷ, ㄱ", "expected": 2, "actual": 2, "pass": True}
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "choice_number", "description": "원 그리기 순서의 정답 선택지"},
        "value": 2,
        "unit": "",
    },
}
