from __future__ import annotations
from modu_math.dsl import Canvas, CircleSlot, LineSlot, ProblemTemplate, RectSlot, Region, TextSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008694",
        title="원의 지름",
        canvas=Canvas(width=960.0, height=720.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.q3",
                    "slot.circle",
                    "slot.pt.ㄱ",
                    "slot.pt.ㄴ",
                    "slot.pt.ㄷ",
                    "slot.pt.ㄹ",
                    "slot.pt.ㅁ",
                    "slot.pt.ㅅ",
                    "slot.pt.ㅇ",
                    "slot.table.border",
                    "slot.table.v1",
                    "slot.table.v2",
                    "slot.table.v3",
                    "slot.table.h1",
                    "slot.table.cell1",
                    "slot.table.cell2",
                    "slot.table.cell3",
                    "slot.table.cell4",
                    "slot.table.cell5",
                    "slot.table.cell6",
                    "slot.arrow",
                    "slot.blank.box",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.pt.ㅁ.copy2",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="    지름을 나타내는 선분을 찾아 길이를 재어 보고, 알 수 있는 점을 ",
                style_role="question",
                x=10,
                y=70,
                font_size=30,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="쓰려고 합니다. ㉠, ㉡, ㉢에 들어갈 알맞은 것을 고르세요.",
                style_role="question",
                x=10,
                y=115,
                font_size=30,
            ),
            CircleSlot(id="slot.circle", prompt="", cx=480, cy=290, r=120, fill="none"),
            LineSlot(id="slot.line.ㄴㅁ", prompt="", x1=480, y1=290, x2=480, y2=170),
            LineSlot(id="slot.line.ㄷㅂ", prompt="", x1=365, y1=290, x2=600, y2=290),
            LineSlot(id="slot.line.ㅁㄷ", prompt="", x1=410, y1=390, x2=550, y2=190),
            LineSlot(id="slot.line.ㅇㅅ", prompt="", x1=560, y1=380, x2=400, y2=200),
            CircleSlot(id="slot.pt.ㅇ", prompt="", cx=480, cy=290, r=5, fill="#d81b60"),
            TextSlot(
                id="slot.pt.ㅇ.label",
                prompt="",
                text="ㅇ",
                style_role="label",
                x=435,
                y=310,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㄱ",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=469,
                y=155,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㄴ",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=370,
                y=195,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㄷ",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=330,
                y=305,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㄹ",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=375,
                y=405,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㅁ",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=565,
                y=405,
                font_size=25,
            ),
            TextSlot(
                id="slot.pt.ㅅ",
                prompt="",
                text="ㅅ",
                style_role="label",
                x=550,
                y=180,
                font_size=25,
            ),
            RectSlot(id="slot.table.border", prompt="", x=165, y=440, width=550, height=85),
            LineSlot(id="slot.table.v1", prompt="", x1=330, y1=440, x2=330, y2=525),
            LineSlot(id="slot.table.v2", prompt="", x1=490, y1=440, x2=490, y2=525),
            LineSlot(id="slot.table.v3", prompt="", x1=630, y1=440, x2=630, y2=525),
            LineSlot(id="slot.table.h1", prompt="", x1=165, y1=485, x2=710, y2=485),
            TextSlot(
                id="slot.table.cell1",
                prompt="",
                text="지름",
                style_role="table",
                x=247.5,
                y=473,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell2",
                prompt="",
                text="선분 ㄴㅁ",
                style_role="table",
                x=410,
                y=473,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell3",
                prompt="",
                text="선분 ㄷㅂ",
                style_role="table",
                x=560,
                y=473,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell4",
                prompt="",
                text="㉠",
                style_role="table",
                x=672.5,
                y=473,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell5",
                prompt="",
                text="길이(cm)",
                style_role="table",
                x=247.5,
                y=516,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell6",
                prompt="",
                text="4",
                style_role="table",
                x=410,
                y=516,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell7",
                prompt="",
                text="4",
                style_role="table",
                x=560,
                y=516,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.table.cell8",
                prompt="",
                text="㉡",
                style_role="table",
                x=672.5,
                y=516,
                font_size=30,
                anchor="middle",
            ),
            TextSlot(
                id="slot.arrow", prompt="", text="⇒", style_role="label", x=170, y=565, font_size=30
            ),
            TextSlot(
                id="slot.q3",
                prompt="",
                text="한 원에서 원의 지름은 모두",
                style_role="question",
                x=215,
                y=570,
                font_size=30,
            ),
            RectSlot(id="slot.blank.box", prompt="", x=575, y=540, width=110, height=35),
            TextSlot(
                id="slot.blank.label",
                prompt="",
                text="㉢",
                style_role="question",
                x=615,
                y=570,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.1",
                prompt="",
                text="① 선분 ㅇㄱ, 2, 다릅니다.",
                style_role="choice",
                x=40,
                y=625,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.2",
                prompt="",
                text="② 선분 ㅇㅁ, 2, 다릅니다.",
                style_role="choice",
                x=520,
                y=625,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.3",
                prompt="",
                text="③ 선분 ㄹㅇ, 4, 같습니다.",
                style_role="choice",
                x=40,
                y=670,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.4",
                prompt="",
                text="④ 선분 ㄹㅅ, 4, 같습니다.",
                style_role="choice",
                x=520,
                y=670,
                font_size=30,
            ),
            TextSlot(
                id="slot.pt.ㅁ.copy2",
                prompt="",
                text="ㅂ",
                x=610,
                y=305,
                font_size=25,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008694",
    "problem_type": "circle_diameter_matching",
    "metadata": {
        "language": "ko",
        "question": "원의 지름과 길이를 보고 알맞은 내용을 고르는 문제",
        "instruction": "㉠, ㉡, ㉢에 들어갈 알맞은 것을 고르세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center", "type": "point", "label": "ㅇ", "role": "center"},
            {"id": "obj.segment.nb", "type": "segment", "label": "선분 ㄴㅁ"},
            {"id": "obj.segment.db", "type": "segment", "label": "선분 ㄷㅂ"},
            {"id": "obj.segment.ls", "type": "segment", "label": "선분 ㄹㅅ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.center",
                    "obj.segment.nb",
                    "obj.segment.db",
                    "obj.segment.ls",
                ],
                "target_ref": "answer.target",
                "condition_refs": ["rel.diameter.same_length", "rel.diameter.passes_center"],
            },
            "plan": {
                "method": "identify_diameter_and_compare_length",
                "description": "원 위의 두 점을 이으면서 중심을 지나는 선분을 지름으로 보고, 같은 원에서는 지름의 길이가 같다는 점을 이용한다.",
            },
            "execute": {
                "expected_operations": [
                    "find_diameter_segments",
                    "compare_lengths",
                    "match_blank_answers",
                ]
            },
            "review": {"check_methods": ["center_crossing_check", "equal_diameter_length_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_blank_completion",
            "description": "㉠, ㉡, ㉢에 들어갈 알맞은 것",
        },
        "value": 4,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008694",
    "problem_type": "circle_diameter_matching",
    "inputs": {
        "total_ticks": 4,
        "target_label": "㉠, ㉡, ㉢",
        "target_ticks": 3,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.segment.nb", "value": {"label": "선분 ㄴㅁ", "length_cm": 4}},
        {"ref": "obj.segment.db", "value": {"label": "선분 ㄷㅂ", "length_cm": 4}},
        {"ref": "obj.segment.ls", "value": {"label": "선분 ㄹㅅ", "length_cm": 4}},
    ],
    "target": {"ref": "answer.target", "type": "multiple_choice_blank_completion"},
    "method": "identify_diameter_and_compare_length",
    "plan": [
        "원 위의 두 점을 이은 선분이면서 중심을 지나는 선분을 찾는다.",
        "지름으로 보이는 선분들의 길이가 같은지 확인한다.",
        "보기에서 조건에 맞는 항목을 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "선분 ㄴㅁ, 선분 ㄷㅂ, 선분 ㄹㅅ는 중심 ㅇ을 지나므로 지름이다.",
            "value": {"diameter_segments": ["선분 ㄴㅁ", "선분 ㄷㅂ", "선분 ㄹㅅ"]},
        },
        {
            "id": "step.2",
            "expr": "한 원에서 지름의 길이는 모두 같다.",
            "value": {"common_length_cm": 4},
        },
        {"id": "step.3", "expr": "보기에서 '선분 ㄹㅅ, 4, 같습니다.'를 찾는다.", "value": 4},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "지름 후보가 중심을 지나는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "지름의 길이가 모두 같은가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_blank_completion",
            "description": "㉠, ㉡, ㉢에 들어갈 알맞은 것",
        },
        "value": 4,
        "unit": "",
    },
}
