from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    LineSlot,
    CircleSlot,
    PathSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008706",
        title="컴퍼스의 침을 꽂지 않은 곳",
        canvas=Canvas(width=960, height=425, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle.main",
                    "slot.arc.tl",
                    "slot.arc.br",
                    "slot.pt.kg",
                    "slot.pt.ng",
                    "slot.pt.dg",
                    "slot.pt.rg",
                    "slot.dot.k1",
                    "slot.dot.n1",
                    "slot.dot.d1",
                    "slot.dot.r1",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="힘찬이가 야구공을 그림과 같은 모양을 그렸습니다. 이 모양을    그릴  ",
                style_role="question",
                x=18.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="때 컴퍼스의 침을 꽂지 않은 곳을 찾아 기호를 선택하세요.",
                style_role="question",
                x=18.0,
                y=66.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.circle.main",
                prompt="",
                cx=425,
                cy=250,
                r=105,
                fill="none",
                stroke="#333333",
                stroke_width=1.6,
            ),
            PathSlot(
                id="slot.arc.tl",
                prompt="",
                d="M 320 250 C 385 245 425 195 425 145",
                fill="none",
                stroke="#333333",
                stroke_width=1.6,
            ),
            PathSlot(
                id="slot.arc.br",
                prompt="",
                d="M 530 250 C 455 255 425 305 425 355",
                fill="none",
                stroke="#333333",
                stroke_width=1.6,
            ),
            CircleSlot(id="slot.pt.kg", prompt="", cx=322, cy=145, r=5, fill="#E91E63"),
            CircleSlot(
                id="slot.pt.ng",
                prompt="",
                cx=532,
                cy=355,
                r=5,
                fill="#E91E63",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(id="slot.pt.dg", prompt="", cx=323, cy=356, r=5, fill="#E91E63"),
            CircleSlot(
                id="slot.pt.rg",
                prompt="",
                cx=426,
                cy=250,
                r=5,
                fill="#E91E63",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.dot.k1",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=300,
                y=135,
                font_size=20,
            ),
            TextSlot(
                id="slot.dot.n1",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=405,
                y=265,
                font_size=20,
            ),
            TextSlot(
                id="slot.dot.d1",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=300,
                y=370,
                font_size=20,
            ),
            TextSlot(
                id="slot.dot.r1",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=535,
                y=370,
                font_size=20,
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=285,
                y1=110,
                x2=285,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=320,
                y1=110,
                x2=320,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=355,
                y1=110,
                x2=355,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=390,
                y1=110,
                x2=390,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=425,
                y1=110,
                x2=425,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=460,
                y1=110,
                x2=460,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=495,
                y1=110,
                x2=495,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=530,
                y1=110,
                x2=530,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=565,
                y1=110,
                x2=565,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=285,
                y1=110,
                x2=565,
                y2=110,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=285,
                y1=145,
                x2=565,
                y2=145,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=285,
                y1=180,
                x2=565,
                y2=180,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=285,
                y1=215,
                x2=565,
                y2=215,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=285,
                y1=250,
                x2=565,
                y2=250,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=285,
                y1=285,
                x2=565,
                y2=285,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=285,
                y1=320,
                x2=565,
                y2=320,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=285,
                y1=355,
                x2=565,
                y2=355,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=285,
                y1=390,
                x2=565,
                y2=390,
                stroke="#2563eb",
                stroke_width=1,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008706",
    "problem_type": "도형_컴퍼스_중심찾기",
    "metadata": {
        "language": "ko",
        "question": "그림과 같은 모양을 그렸을 때 컴퍼스의 침을 꽂지 않은 곳을 찾는 문제",
        "instruction": "기호를 선택하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.shape", "type": "figure", "name": "야구공 모양"},
            {"id": "obj.choice.k", "type": "candidate_point", "label": "ㄱ"},
            {"id": "obj.choice.n", "type": "candidate_point", "label": "ㄴ"},
            {"id": "obj.choice.d", "type": "candidate_point", "label": "ㄷ"},
            {"id": "obj.choice.r", "type": "candidate_point", "label": "ㄹ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.shape", "rel.choice"],
                "target_ref": "answer.target",
                "condition_refs": [],
            },
            "plan": {
                "method": "figure_based_selection",
                "description": "그림에서 컴퍼스의 침을 꽂지 않은 위치에 해당하는 기호를 찾는다.",
            },
            "execute": {
                "expected_operations": ["identify_candidate_points", "match_visible_explanation"]
            },
            "review": {"check_methods": ["answer_matches_printed_mark"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_symbol", "description": "컴퍼스의 침을 꽂지 않은 곳의 기호"},
        "value": 3,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008706",
    "problem_type": "도형_컴퍼스_중심찾기",
    "inputs": {
        "total_ticks": 0,
        "target_label": "컴퍼스의 침을 꽂지 않은 곳",
        "target_ticks": 1,
        "target_count": 4,
        "unit": "",
    },
    "given": [
        {"ref": "obj.shape", "value": {"name": "야구공 모양"}},
        {"ref": "obj.choice.k", "value": {"label": "ㄱ"}},
        {"ref": "obj.choice.n", "value": {"label": "ㄴ"}},
        {"ref": "obj.choice.d", "value": {"label": "ㄷ"}},
        {"ref": "obj.choice.r", "value": {"label": "ㄹ"}},
    ],
    "target": {"ref": "answer.target", "type": "selected_symbol"},
    "method": "figure_based_selection",
    "plan": [
        "그림에서 보이는 후보 기호를 확인한다.",
        "인쇄된 해설과 정답 표기를 기준으로 선택 결과를 정리한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "인쇄된 정답 표기 확인", "value": "ㄷ"},
        {
            "id": "step.2",
            "expr": "인쇄된 해설 확인",
            "value": "점 ㄷ을 원의 중심으로 하여 그린 원은 없습니다.",
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정답 표기가 ㄷ인지 확인",
            "expected": "ㄷ",
            "actual": "ㄷ",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "selected_symbol", "description": "컴퍼스의 침을 꽂지 않은 곳의 기호"},
        "value": 3,
        "unit": "",
    },
}
