from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008716",
        title="도형에 대한 설명으로 틀린 것은 어느 것일까요?",
        canvas=Canvas(width=760.0, height=490.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.title",
                    "slot.fig.circle",
                    "slot.fig.line.gn",
                    "slot.fig.line.nl",
                    "slot.fig.line.od",
                    "slot.fig.line.oo",
                    "slot.fig.pt.o",
                    "slot.fig.lb.g",
                    "slot.fig.lb.n",
                    "slot.fig.lb.l",
                    "slot.fig.lb.d",
                    "slot.fig.lb.o",
                    "slot.choice.1.num",
                    "slot.choice.1.text",
                    "slot.choice.2.num",
                    "slot.choice.2.text",
                    "slot.choice.3.num",
                    "slot.choice.3.text",
                    "slot.choice.4.num",
                    "slot.choice.4.text",
                    "slot.choice.5.num",
                    "slot.choice.5.text",
                    "slot.inserted.text_box.1",
                    "slot.inserted.text_box.1.copy1",
                    "slot.inserted.text_box.1.copy1.copy2",
                    "slot.inserted.text_box.1.copy1.copy2.copy3",
                    "slot.inserted.text_box.1.copy1.copy2.copy3.copy4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.title",
                prompt="",
                text="도형에 대한 설명으로 틀린 것은 어느 것일까요?",
                style_role="question",
                x=14.0,
                y=30.0,
                font_size=28,
            ),
            CircleSlot(id="slot.fig.circle", prompt="", cx=330, cy=170, r=90, fill="none"),
            LineSlot(id="slot.fig.line.gn", prompt="", x1=315, y1=82, x2=410, y2=127),
            LineSlot(id="slot.fig.line.nl", prompt="", x1=250, y1=212, x2=410, y2=127),
            LineSlot(id="slot.fig.line.od", prompt="", x1=330, y1=172, x2=385, y2=242),
            LineSlot(id="slot.fig.line.oo", prompt="", x1=556.0, y1=89.0, x2=556.0, y2=89.0),
            CircleSlot(
                id="slot.fig.pt.o",
                prompt="",
                cx=330,
                cy=170,
                r=5,
                fill="#EC407A",
                stroke="#111111",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.fig.lb.g",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=295,
                y=82,
                font_size=25,
            ),
            TextSlot(
                id="slot.fig.lb.n",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=225,
                y=227,
                font_size=25,
            ),
            TextSlot(
                id="slot.fig.lb.l",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=410,
                y=132,
                font_size=25,
            ),
            TextSlot(
                id="slot.fig.lb.d",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=390,
                y=257,
                font_size=25,
            ),
            TextSlot(
                id="slot.fig.lb.o",
                prompt="",
                text="ㅇ",
                style_role="label",
                x=320,
                y=157,
                font_size=20,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.1.num",
                prompt="",
                text="①",
                style_role="choice",
                x=30,
                y=310,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.1.text",
                prompt="",
                text="원의 중심은 점 ㅇ입니다.",
                style_role="choice",
                x=70,
                y=305,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.2.num",
                prompt="",
                text="②",
                style_role="choice",
                x=240,
                y=370,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.2.text",
                prompt="",
                text="원의 지름은 선분 ㄴㄹ입니다.",
                style_role="choice",
                x=415,
                y=305,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.3.num",
                prompt="",
                text="③",
                style_role="choice",
                x=125,
                y=365,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.3.text",
                prompt="",
                text="선분 ㄴㅇ은 원의 반지름입니다.",
                style_role="choice",
                x=465,
                y=370,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.4.num",
                prompt="",
                text="④",
                style_role="choice",
                x=30,
                y=425,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.4.text",
                prompt="",
                text="길이가 가장 긴 선분은 선분 ㄱㄹ입니다.",
                style_role="choice",
                x=465,
                y=425,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.5.num",
                prompt="",
                text="⑤",
                style_role="choice",
                x=115,
                y=460,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.5.text",
                prompt="",
                text="선분 ㄷㅇ과 선분 ㄹㅇ의 길이는 같습니다.",
                style_role="choice",
                x=340,
                y=470,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.inserted.text_box.1",
                prompt="",
                text="    1. 원의 중심은    점 ㅇ입니다.  ",
                x=35,
                y=320,
                font_size=25,
                fill="#111827",
            ),
            TextSlot(
                id="slot.inserted.text_box.1.copy1",
                prompt="",
                text="2. 원의 지름은 선분 ㄴㄹ입니다.",
                x=345,
                y=320,
                font_size=25,
                fill="#111827",
            ),
            TextSlot(
                id="slot.inserted.text_box.1.copy1.copy2",
                prompt="",
                text="3. 선분ㄴㅇ은 원의 반지름입니다.",
                x=35,
                y=365,
                font_size=25,
                fill="#111827",
            ),
            TextSlot(
                id="slot.inserted.text_box.1.copy1.copy2.copy3",
                prompt="",
                text="4. 길이가 가장 긴 선분은 선분 ㄱㄹ입니다. ",
                x=35,
                y=407,
                font_size=25,
                fill="#111827",
            ),
            TextSlot(
                id="slot.inserted.text_box.1.copy1.copy2.copy3.copy4",
                prompt="",
                text="5. 선분 ㄷㅇ과 선분ㄹㅇ의 길이는 같습니다.",
                x=35,
                y=445,
                font_size=25,
                fill="#111827",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008716",
    "problem_type": "도형의 성질_원",
    "metadata": {
        "language": "ko",
        "question": "도형에 대한 설명으로 틀린 것은 어느 것일까요?",
        "instruction": "보기 중 옳지 않은 설명을 고른다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center", "type": "point", "label": "O"},
            {"id": "obj.point_g", "type": "point", "label": "ㄱ"},
            {"id": "obj.point_n", "type": "point", "label": "ㄴ"},
            {"id": "obj.point_l", "type": "point", "label": "ㄹ"},
            {"id": "obj.point_d", "type": "point", "label": "ㄷ"},
            {
                "id": "obj.segment_nl",
                "type": "segment",
                "endpoints": ["obj.point_n", "obj.point_l"],
            },
            {"id": "obj.segment_no", "type": "segment", "endpoints": ["obj.point_n", "obj.center"]},
            {"id": "obj.segment_do", "type": "segment", "endpoints": ["obj.point_d", "obj.center"]},
            {"id": "obj.segment_ro", "type": "segment", "endpoints": ["obj.point_l", "obj.center"]},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": [
                    "obj.circle",
                    "obj.center",
                    "obj.segment_nl",
                    "obj.segment_no",
                    "obj.segment_do",
                    "obj.segment_ro",
                ],
                "target_ref": "answer.target",
                "condition_refs": [
                    "rel.center_of_circle",
                    "rel.diameter",
                    "rel.radius_1",
                    "rel.radius_2",
                    "rel.radius_3",
                ],
            },
            "plan": {
                "method": "원의 성질 확인",
                "description": "중심, 지름, 반지름의 관계를 보고 보기 문장 중 틀린 것을 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "center_identification",
                    "diameter_identification",
                    "radius_identification",
                    "compare_segment_lengths",
                ]
            },
            "review": {"check_methods": ["circle_property_check", "largest_segment_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "incorrect_statement", "description": "도형에 대한 설명으로 틀린 것"},
        "value": 4,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008716",
    "problem_type": "도형의 성질_원",
    "inputs": {
        "total_ticks": 1,
        "target_label": "틀린 설명",
        "target_ticks": 4,
        "target_count": 5,
        "unit": "",
    },
    "given": [
        {"ref": "obj.center", "value": {"label": "O"}},
        {"ref": "obj.segment_nl", "value": {"type": "diameter"}},
        {"ref": "obj.segment_no", "value": {"type": "radius"}},
        {"ref": "obj.segment_do", "value": {"type": "radius"}},
        {"ref": "obj.segment_ro", "value": {"type": "radius"}},
    ],
    "target": {"ref": "answer.target", "type": "incorrect_statement"},
    "method": "원의 성질 확인",
    "plan": [
        "원의 중심, 지름, 반지름의 관계를 확인한다.",
        "보기 문장 중 원의 성질과 맞지 않는 것을 찾는다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "원의 중심은 점 O", "value": True},
        {"id": "step.2", "expr": "선분 ㄴㄹ은 지름", "value": True},
        {"id": "step.3", "expr": "선분 ㄴO은 반지름", "value": True},
        {"id": "step.4", "expr": "가장 긴 선분은 선분 ㄱㄹ", "value": False},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "지름은 반지름보다 길다",
            "expected": True,
            "actual": True,
            "pass": True,
        },
        {"id": "check.2", "expr": "틀린 보기는 ④", "expected": 4, "actual": 4, "pass": True},
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "incorrect_statement", "description": "도형에 대한 설명으로 틀린 것"},
        "value": 4,
        "unit": "",
    },
}
