from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008671",
        title="원을 가장 크게 그릴 수 있는 구멍 고르기",
        canvas=Canvas(width=800.0, height=360.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q1", "slot.q2"),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.bar",
                    "slot.tool",
                    "slot.hole.1",
                    "slot.hole.2",
                    "slot.hole.3",
                    "slot.hole.4",
                    "slot.hole.5",
                    "slot.link.1",
                    "slot.link.2",
                    "slot.link.3",
                    "slot.link.4",
                    "slot.choice.1",
                    "slot.choice.2",
                    "slot.choice.3",
                    "slot.choice.4",
                    "slot.choice.lb.1",
                    "slot.choice.lb.2",
                    "slot.choice.lb.3",
                    "slot.choice.lb.4",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="누름 못과 띠 종이를 사용하여 원을 그리려고 합니다.",
                style_role="question",
                x=15,
                y=41,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="원을 가장 크게 그리려면 어느 구멍에 연필을 꽂아야 하는지 알맞은 기호를 선택하세요.",
                style_role="question",
                x=15,
                y=74,
                font_size=30,
                fill="#111111",
            ),
            RectSlot(
                id="slot.bar",
                prompt="",
                x=175,
                y=210,
                width=435,
                height=40,
                fill="#bfeaed",
                stroke="#8fcfd0",
                stroke_width=1.0,
            ),
            CircleSlot(
                id="slot.tool",
                prompt="",
                cx=230,
                cy=230,
                r=10,
                fill="#7f8c99",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.hole.1",
                prompt="",
                cx=275,
                cy=230,
                r=5,
                fill="#ffffff",
                stroke="#8a8a8a",
                stroke_width=1.0,
            ),
            CircleSlot(
                id="slot.hole.2",
                prompt="",
                cx=340,
                cy=230,
                r=5,
                fill="#ffffff",
                stroke="#8a8a8a",
                stroke_width=1.0,
            ),
            CircleSlot(
                id="slot.hole.3",
                prompt="",
                cx=400,
                cy=230,
                r=5,
                fill="#ffffff",
                stroke="#8a8a8a",
                stroke_width=1.0,
            ),
            CircleSlot(
                id="slot.hole.4",
                prompt="",
                cx=460,
                cy=230,
                r=5,
                fill="#ffffff",
                stroke="#8a8a8a",
                stroke_width=1.0,
            ),
            LineSlot(
                id="slot.link.1",
                prompt="",
                x1=275,
                y1=235,
                x2=275,
                y2=270,
                stroke="#ff6bb6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.link.2",
                prompt="",
                x1=340,
                y1=235,
                x2=340,
                y2=270,
                stroke="#ff6bb6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.link.3",
                prompt="",
                x1=400,
                y1=235,
                x2=400,
                y2=270,
                stroke="#ff6bb6",
                stroke_width=2.0,
            ),
            LineSlot(
                id="slot.link.4",
                prompt="",
                x1=460,
                y1=235,
                x2=460,
                y2=270,
                stroke="#ff6bb6",
                stroke_width=2.0,
            ),
            TextSlot(
                id="slot.choice.lb.1",
                prompt="",
                text="㉠",
                style_role="label",
                x=262,
                y=290,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.lb.2",
                prompt="",
                text="㉡",
                style_role="label",
                x=327,
                y=290,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.lb.3",
                prompt="",
                text="㉢",
                style_role="label",
                x=387,
                y=290,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice.lb.4",
                prompt="",
                text="㉣",
                style_role="label",
                x=447,
                y=290,
                font_size=25,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008671",
    "problem_type": "choice_selection",
    "metadata": {
        "language": "ko",
        "question": "누름 못과 띠 종이를 사용하여 원을 그리려고 합니다. 원을 가장 크게 그리려면 어느 구멍에 연필을 꽂아야 하는지 알맞은 기호를 선택하세요.",
        "instruction": "구멍의 기호를 선택하시오.",
        "points": 5,
    },
    "domain": {
        "objects": [
            {"id": "obj.tool", "type": "center_tool"},
            {"id": "obj.hole_positions", "type": "ordered_holes", "count": 5},
            {
                "id": "obj.choice_labels",
                "type": "labels",
                "labels": ["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"],
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.tool", "obj.hole_positions"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.radius_vs_distance"],
            },
            "plan": {
                "method": "compare_hole_distances",
                "description": "연필심과 중심점 사이의 거리가 가장 큰 구멍을 고른다.",
            },
            "execute": {"expected_operations": ["compare_positions", "select_farthest_hole"]},
            "review": {"check_methods": ["distance_order_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_label",
            "description": "원을 가장 크게 그릴 수 있는 구멍의 기호",
        },
        "value": "ㄹ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008671",
    "problem_type": "choice_selection",
    "inputs": {
        "total_ticks": 5,
        "target_label": "ㅁ",
        "target_ticks": 5,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {
            "ref": "obj.hole_positions",
            "value": {"count": 5, "labels": ["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"]},
        },
        {"ref": "obj.tool", "value": {"type": "center_tool"}},
    ],
    "target": {"ref": "answer.target", "type": "choice_label"},
    "method": "compare_hole_distances",
    "plan": [
        "구멍들의 위치를 비교한다.",
        "누름 못과 연필심 사이가 가장 멀어지는 구멍을 찾는다.",
        "그 구멍에 대응하는 기호를 답으로 둔다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "구멍 위치를 왼쪽에서 오른쪽으로 비교한다.",
            "value": "ㄱ, ㄴ, ㄷ, ㄹ, ㅁ",
        },
        {"id": "step.2", "expr": "가장 멀리 있는 구멍을 고른다.", "value": "ㅁ"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "가장 먼 위치가 마지막 구멍인지 확인한다.",
            "expected": "ㄹ",
            "actual": "ㄹ",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "choice_label",
            "description": "원을 가장 크게 그릴 수 있는 구멍의 기호",
        },
        "value": "ㄹ",
        "unit": "",
    },
}
