from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008717",
        title="원의 규칙을 바르게 말한 사람",
        canvas=Canvas(width=940, height=530, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.v9",
                    "slot.graphpaper.v10",
                    "slot.graphpaper.v11",
                    "slot.graphpaper.v12",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                    "slot.graphpaper.h9",
                    "slot.graphpaper.h10",
                    "slot.graphpaper.h11",
                    "slot.graphpaper.h12",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=("slot.pt.center", "slot.circle1", "slot.circle2", "slot.circle3"),
            ),
            Region(
                id="region.statements",
                role="body",
                flow="absolute",
                slot_ids=("slot.box", "slot.s1", "slot.s2", "slot.s3"),
            ),
            Region(id="region.answer", role="footer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="규칙에 따라 원을 그린 것입니다. 그린 규칙을 바르게 말한 사람을  ",
                style_role="question",
                x=14.0,
                y=28.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="선택하세요.",
                style_role="question",
                x=14.0,
                y=62.0,
                font_size=28,
            ),
            CircleSlot(id="slot.circle1", prompt="", cx=475, cy=206, r=20, fill="none"),
            CircleSlot(id="slot.circle2", prompt="", cx=475, cy=206, r=60, fill="none"),
            CircleSlot(id="slot.circle3", prompt="", cx=475, cy=206, r=100, fill="none"),
            CircleSlot(
                id="slot.pt.center",
                prompt="",
                cx=476,
                cy=207,
                r=4,
                fill="#ff4aa2",
                stroke="#111111",
                stroke_width=2,
            ),
            RectSlot(
                id="slot.box",
                prompt="",
                x=20,
                y=345,
                width=885,
                height=90,
                fill="none",
                stroke="#7DAA00",
                stroke_width=1.4,
            ),
            TextSlot(
                id="slot.s1",
                prompt="",
                text="정은: 원의 중심이 모두 다르고 반지름이 모두 1칸씩 늘어나게 그렸어.",
                style_role="body",
                x=35,
                y=380,
                font_size=30,
            ),
            TextSlot(
                id="slot.s2",
                prompt="",
                text="민수: 원의 중심이 모두 같고 반지름이 모두 2칸씩 늘어나게 그렸어.",
                style_role="body",
                x=35,
                y=420,
                font_size=30,
            ),
            TextSlot(
                id="slot.s3",
                prompt="",
                text="( 정은 , 민수 )",
                style_role="body",
                x=350,
                y=475,
                font_size=30,
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=355,
                y1=86,
                x2=355,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=375,
                y1=86,
                x2=375,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=395,
                y1=86,
                x2=395,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=415,
                y1=86,
                x2=415,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=435,
                y1=86,
                x2=435,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=455,
                y1=86,
                x2=455,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=475,
                y1=86,
                x2=475,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=495,
                y1=86,
                x2=495,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=515,
                y1=86,
                x2=515,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v9",
                prompt="",
                x1=535,
                y1=86,
                x2=535,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v10",
                prompt="",
                x1=555,
                y1=86,
                x2=555,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v11",
                prompt="",
                x1=575,
                y1=86,
                x2=575,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v12",
                prompt="",
                x1=595,
                y1=86,
                x2=595,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=355,
                y1=86,
                x2=595,
                y2=86,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=355,
                y1=106,
                x2=595,
                y2=106,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=355,
                y1=126,
                x2=595,
                y2=126,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=355,
                y1=146,
                x2=595,
                y2=146,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=355,
                y1=166,
                x2=595,
                y2=166,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=355,
                y1=186,
                x2=595,
                y2=186,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=355,
                y1=206,
                x2=595,
                y2=206,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=355,
                y1=226,
                x2=595,
                y2=226,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=355,
                y1=246,
                x2=595,
                y2=246,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h9",
                prompt="",
                x1=355,
                y1=266,
                x2=595,
                y2=266,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h10",
                prompt="",
                x1=355,
                y1=286,
                x2=595,
                y2=286,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h11",
                prompt="",
                x1=355,
                y1=306,
                x2=595,
                y2=306,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h12",
                prompt="",
                x1=355,
                y1=326,
                x2=595,
                y2=326,
                stroke="#2563eb",
                stroke_width=1,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008717",
    "problem_type": "pattern_identification",
    "metadata": {
        "language": "ko",
        "question": "규칙에 따라 그린 원의 규칙을 바르게 말한 사람을 선택하는 문제",
        "instruction": "그린 규칙을 바르게 말한 사람을 선택하세요.",
    },
    "domain": {
        "objects": [
            {
                "id": "obj.circle_set",
                "type": "circle_pattern",
                "description": "같은 중심을 기준으로 반복되는 원들",
            },
            {
                "id": "obj.jungeun_statement",
                "type": "statement",
                "speaker": "정은",
                "description": "원의 중심이 모두 다르고 반지름이 모두 1칸씩 늘어난다고 말함",
            },
            {
                "id": "obj.minsu_statement",
                "type": "statement",
                "speaker": "민수",
                "description": "원의 중심이 모두 같고 반지름이 모두 2칸씩 늘어난다고 말함",
            },
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle_set", "obj.jungeun_statement", "obj.minsu_statement"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.center_same", "rel.radius_growth"],
            },
            "plan": {
                "method": "pattern_matching",
                "description": "그림의 원이 같은 중심인지와 반지름이 일정한 칸수씩 늘어나는지 비교한다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_centers",
                    "compare_radius_growth",
                    "match_statement_to_pattern",
                ]
            },
            "review": {"check_methods": ["statement_consistency_check", "pattern_rule_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_choice", "description": "그린 규칙을 바르게 말한 사람"},
        "value": 2,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008717",
    "problem_type": "pattern_identification",
    "inputs": {
        "total_ticks": 3,
        "target_label": "그린 규칙을 바르게 말한 사람",
        "target_ticks": 1,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle_set", "value": {"description": "같은 중심을 가진 원들의 집합"}},
        {
            "ref": "obj.jungeun_statement",
            "value": {
                "speaker": "정은",
                "content": "원의 중심이 모두 다르고 반지름이 모두 1칸씩 늘어나게 그렸어.",
            },
        },
        {
            "ref": "obj.minsu_statement",
            "value": {
                "speaker": "민수",
                "content": "원의 중심이 모두 같고 반지름이 모두 2칸씩 늘어나게 그렸어.",
            },
        },
    ],
    "target": {"ref": "answer.target", "type": "person_choice"},
    "method": "pattern_matching",
    "plan": [
        "그림의 원들이 같은 중심을 공유하는지 확인한다.",
        "반지름이 일정한 칸수씩 늘어나는지 비교한다.",
        "두 학생의 설명 중 그림과 맞는 사람을 고른다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "그림의 원들은 같은 중심을 공유한다", "value": True},
        {"id": "step.2", "expr": "반지름은 1칸, 3칸, 5칸처럼 2칸씩 커진다", "value": True},
        {"id": "step.3", "expr": "민수의 설명과 일치하는지 확인한다", "value": True},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "정은의 설명은 그림의 규칙과 일치하는가",
            "expected": False,
            "actual": False,
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "민수의 설명은 그림의 규칙과 일치하는가",
            "expected": True,
            "actual": True,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "person_choice", "description": "그린 규칙을 바르게 말한 사람"},
        "value": 2,
        "unit": "",
    },
}
