from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008669",
        title="원의 중심과 반지름",
        canvas=Canvas(width=960, height=500, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.choice_box",
                    "slot.choice.a.outer",
                    "slot.choice.a.left",
                    "slot.choice.a.right",
                    "slot.choice.b.outer",
                    "slot.choice.b.middle",
                    "slot.choice.b.inner",
                    "slot.choice.c.outer",
                    "slot.choice.c.inner",
                    "slot.choice.b.inner.copy1",
                    "slot.q1.copy2",
                    "slot.q1.copy2.copy3",
                    "slot.q1.copy2.copy3.copy4",
                    "slot.q1.copy2.copy3.copy5",
                ),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="    원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것을 찾아",
                style_role="question",
                x=20,
                y=75,
                font_size=30,
            ),
            RectSlot(
                id="slot.choice_box",
                prompt="",
                x=75,
                y=195,
                width=690,
                height=130,
                fill="none",
                stroke="#A89BEA",
            ),
            CircleSlot(
                id="slot.choice.a.outer",
                prompt="",
                cx=240,
                cy=263,
                r=50,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.a.left",
                prompt="",
                cx=215,
                cy=264,
                r=25,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.a.right",
                prompt="",
                cx=264,
                cy=264,
                r=25,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.outer",
                prompt="",
                cx=435,
                cy=265,
                r=45,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.middle",
                prompt="",
                cx=435,
                cy=265,
                r=30,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.inner",
                prompt="",
                cx=435,
                cy=265,
                r=15,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.c.outer",
                prompt="",
                cx=620,
                cy=260,
                r=45,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.c.inner",
                prompt="",
                cx=620,
                cy=275,
                r=30,
                fill="none",
                stroke="#333333",
            ),
            CircleSlot(
                id="slot.choice.b.inner.copy1",
                prompt="",
                cx=620,
                cy=290,
                r=15,
                stroke="#333333",
                stroke_width=2,
            ),
            TextSlot(
                id="slot.q1.copy2",
                prompt="",
                text="   선택하세요.    ",
                x=20,
                y=125,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy2.copy3",
                prompt="",
                text="㉠",
                x=140,
                y=235,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy2.copy3.copy4",
                prompt="",
                text="㉡",
                x=340,
                y=235,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.q1.copy2.copy3.copy5",
                prompt="",
                text="㉢",
                x=525,
                y=235,
                font_size=30,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008669",
    "problem_type": "도형_판별",
    "metadata": {
        "language": "ko",
        "question": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것을 찾아 선택하세요.",
        "instruction": "정답을 고르기",
    },
    "domain": {
        "objects": [
            {"id": "obj.choice_1", "type": "circle_figure"},
            {"id": "obj.choice_2", "type": "circle_figure"},
            {"id": "obj.choice_3", "type": "circle_figure"},
            {"id": "obj.example", "type": "circle_figure"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.choice_1", "obj.choice_2", "obj.choice_3"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.center_same", "rel.radius_different"],
            },
            "plan": {
                "method": "도형 비교",
                "description": "각 그림에서 중심이 같은지와 반지름만 달라졌는지를 비교한다.",
            },
            "execute": {"expected_operations": ["중심 비교", "반지름 비교", "해설 문장 확인"]},
            "review": {"check_methods": ["중심 이동 여부 확인", "반지름만 변화했는지 확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_figure",
            "description": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것",
        },
        "value": "㉡",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008669",
    "problem_type": "도형_판별",
    "inputs": {
        "total_ticks": 3,
        "target_label": "정답",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.choice_1", "value": "도형 선택지 1"},
        {"ref": "obj.choice_2", "value": "도형 선택지 2"},
        {"ref": "obj.choice_3", "value": "도형 선택지 3"},
    ],
    "target": {"ref": "answer.target", "type": "selected_figure"},
    "method": "도형 비교",
    "plan": [
        "그림마다 원의 중심이 같은지 확인한다.",
        "반지름만 다르게 그린 그림인지 비교한다.",
        "해설에 맞는 그림을 선택한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "선택지 1은 중심이 이동한 그림인지 확인",
            "value": "중심 이동",
        },
        {
            "id": "step.2",
            "expr": "선택지 2는 중심은 같고 반지름만 다른지 확인",
            "value": "중심 같음, 반지름 다름",
        },
        {
            "id": "step.3",
            "expr": "선택지 3은 중심이 이동한 그림인지 확인",
            "value": "중심 이동",
        },
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "해설과 일치하는 선택지인지 확인",
            "expected": "선택지 2",
            "actual": "선택지 2",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_figure",
            "description": "원의 중심을 옮기지 않고 반지름만 다르게 하여 그린 것",
        },
        "value": "㉡",
        "unit": "",
    },
}
