from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    RectSlot,
    CircleSlot,
    LineSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008660",
        title="원의 반지름 찾기",
        canvas=Canvas(width=952, height=406, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=("slot.q_text_1",),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle",
                    "slot.center",
                    "slot.pt.a",
                    "slot.pt.c",
                    "slot.lb.o",
                    "slot.lb.ga",
                    "slot.lb.na",
                    "slot.lb.da",
                    "slot.lb.ra",
                    "slot.seg.1",
                    "slot.seg.2",
                    "slot.seg.3",
                    "slot.seg.4",
                    "slot.pt.c.copy5",
                    "slot.pt.c.copy6",
                ),
            ),
            Region(
                id="region.choices",
                role="choices",
                flow="absolute",
                slot_ids=(
                    "slot.choice.ga",
                    "slot.choice.na",
                    "slot.choice.da",
                    "slot.choice.ra",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q_text_1",
                prompt="",
                text="\n그림에서 원의 반지름을 나타내는 선분을 찾아 기호를 모두 선택해\n보세요.",
                style_role="question",
                x=55,
                y=20,
                font_size=30,
                fill="#111111",
            ),
            CircleSlot(
                id="slot.circle",
                prompt="",
                cx=480,
                cy=175,
                r=90,
                fill="none",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(id="slot.center", prompt="", cx=480, cy=175, r=5, fill="#ff4fa3"),
            CircleSlot(id="slot.pt.a", prompt="", cx=418.0, cy=110.0, r=2.8, fill="#222222"),
            CircleSlot(
                id="slot.pt.c",
                prompt="",
                cx=560,
                cy=215,
                r=2.8,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            LineSlot(
                id="slot.seg.1",
                prompt="",
                x1=420,
                y1=110,
                x2=480,
                y2=175,
                stroke="#222222",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.seg.2",
                prompt="",
                x1=420,
                y1=110,
                x2=500,
                y2=260,
                stroke="#222222",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.seg.3",
                prompt="",
                x1=415,
                y1=235,
                x2=560,
                y2=215,
                stroke="#222222",
                stroke_width=1.5,
            ),
            LineSlot(
                id="slot.seg.4",
                prompt="",
                x1=415,
                y1=235,
                x2=480,
                y2=175,
                stroke="#222222",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.lb.o", prompt="", text="ㅇ", style_role="label", x=475, y=155, font_size=25
            ),
            TextSlot(
                id="slot.lb.ga",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=390,
                y=110,
                font_size=25,
            ),
            TextSlot(
                id="slot.lb.na",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=395,
                y=255,
                font_size=25,
            ),
            TextSlot(
                id="slot.lb.da",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=510,
                y=280,
                font_size=25,
            ),
            TextSlot(
                id="slot.lb.ra",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=590,
                y=210,
                font_size=25,
            ),
            TextSlot(
                id="slot.choice.ga",
                prompt="",
                text="⑴  선분  ㅇㄱ",
                style_role="choice",
                x=60,
                y=320,
                font_size=30,
                max_width=825,
            ),
            TextSlot(
                id="slot.choice.na",
                prompt="",
                text="⑵  선분  ㅇㄴ",
                style_role="choice",
                x=285,
                y=320,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.da",
                prompt="",
                text="⑶  선분  ㄱㄷ",
                style_role="choice",
                x=510,
                y=320,
                font_size=30,
            ),
            TextSlot(
                id="slot.choice.ra",
                prompt="",
                text="⑷  선분  ㄴㄹ",
                style_role="choice",
                x=720,
                y=320,
                font_size=30,
            ),
            CircleSlot(
                id="slot.pt.c.copy5",
                prompt="",
                cx=414,
                cy=236,
                r=2.8,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
            CircleSlot(
                id="slot.pt.c.copy6",
                prompt="",
                cx=500,
                cy=262,
                r=2.8,
                fill="#222222",
                stroke="#111111",
                stroke_width=2,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008660",
    "problem_type": "geometry_radius_selection",
    "metadata": {
        "language": "ko",
        "question": "그림에서 원의 반지름을 나타내는 선분을 찾아 기호를 모두 선택해 보세요.",
        "instruction": "기호를 모두 선택하시오.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.center", "type": "center", "label": "ㅇ"},
            {"id": "obj.radius_candidate_1", "type": "segment", "label": "ㅇㄱ"},
            {"id": "obj.radius_candidate_2", "type": "segment", "label": "ㅇㄴ"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.center"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.radius_from_center_to_point"],
            },
            "plan": {
                "method": "identify_radius_by_center_and_point",
                "description": "원의 중심과 원 위의 점을 잇는 선분을 반지름으로 찾는다.",
            },
            "execute": {
                "expected_operations": [
                    "compare_center_to_boundary_segments",
                    "select_radius_labels",
                ]
            },
            "review": {"check_methods": ["center_to_circle_boundary_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_labels",
            "description": "원의 반지름을 나타내는 선분의 보기 기호",
        },
        "value": "⑴  선분  ㅇㄱ, ⑵  선분  ㅇㄴ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008660",
    "problem_type": "geometry_radius_selection",
    "inputs": {
        "total_ticks": 0,
        "target_label": "원의 반지름을 나타내는 선분",
        "target_ticks": 0,
        "target_count": 2,
        "unit": "",
    },
    "given": [
        {"ref": "obj.center", "value": {"label": "ㅇ"}},
        {"ref": "obj.radius_candidate_1", "value": {"label": "ㅇㄱ"}},
        {"ref": "obj.radius_candidate_2", "value": {"label": "ㅇㄴ"}},
    ],
    "target": {"ref": "answer.target", "type": "multiple_choice_labels"},
    "method": "identify_radius_by_center_and_point",
    "plan": [
        "원의 중심 ㅇ에서 원 위의 점으로 이어진 선분을 찾는다.",
        "반지름에 해당하는 보기 기호를 고른다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "원의 중심 ㅇ과 원 위의 점을 잇는 선분 확인",
            "value": "ㅇㄱ, ㅇㄴ",
        },
        {"id": "step.2", "expr": "반지름에 해당하는 보기 기호 선택", "value": "가, 나"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "중심 ㅇ을 포함하고 원 위의 점까지 이어지는 선분인지 확인",
            "expected": True,
            "actual": True,
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "multiple_choice_labels",
            "description": "원의 반지름을 나타내는 선분의 보기 기호",
        },
        "value": "⑴  선분  ㅇㄱ, ⑵  선분  ㅇㄴ",
        "unit": "",
    },
}
