from __future__ import annotations
from modu_math.dsl import (
    Canvas,
    ProblemTemplate,
    Region,
    TextSlot,
    CircleSlot,
    LineSlot,
    RectSlot,
    PathSlot,
)


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008696",
        title="원을 둘로 똑같이 나누는 선분",
        canvas=Canvas(width=950.0, height=560.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q.title",
                    "slot.fig1.v",
                    "slot.fig2.v",
                    "slot.fig2.h",
                    "slot.fig3.v",
                    "slot.fig3.h",
                    "slot.fig3.center",
                    "slot.arrow1",
                    "slot.arrow2",
                    "slot.desc1.1",
                    "slot.desc1.2",
                    "slot.desc1.3",
                    "slot.desc1.4",
                    "slot.desc2.1",
                    "slot.desc2.2",
                    "slot.desc2.3",
                    "slot.desc2.4",
                    "slot.desc3.1",
                    "slot.desc3.2",
                    "slot.desc3.3",
                    "slot.desc3.4",
                ),
            ),
            Region(
                id="region.item1",
                role="stem",
                flow="absolute",
                slot_ids=("slot.item1.q", "slot.item1.q.copy3.copy1"),
            ),
        ),
        slots=(
            TextSlot(
                id="slot.q.title",
                prompt="",
                text="원을 둘로 똑같이 나누는 선분을 알아보려고 합니다. 알맞은말을 선택하세요.",
                style_role="question",
                x=20,
                y=30,
                font_size=30,
            ),
            CircleSlot(
                id="slot.fig1.circle", prompt="", cx=180.0, cy=136.0, r=56.0, fill="#ffeef2"
            ),
            LineSlot(
                id="slot.fig1.v",
                prompt="",
                x1=180.0,
                y1=84.0,
                x2=180.0,
                y2=188.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(
                id="slot.fig2.circle", prompt="", cx=443.0, cy=136.0, r=56.0, fill="#ffeef2"
            ),
            LineSlot(
                id="slot.fig2.v",
                prompt="",
                x1=443.0,
                y1=84.0,
                x2=443.0,
                y2=188.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            LineSlot(
                id="slot.fig2.h",
                prompt="",
                x1=391.0,
                y1=136.0,
                x2=495.0,
                y2=136.0,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(id="slot.fig3.circle", prompt="", cx=745, cy=135, r=55, fill="#ffeef2"),
            LineSlot(
                id="slot.fig3.v",
                prompt="",
                x1=745,
                y1=85,
                x2=745,
                y2=190,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            LineSlot(
                id="slot.fig3.h",
                prompt="",
                x1=690,
                y1=135,
                x2=800,
                y2=135,
                stroke="#ff9db3",
                stroke_dasharray="5 4",
            ),
            CircleSlot(id="slot.fig3.center", prompt="", cx=746, cy=135, r=5, fill="#ff5b8d"),
            TextSlot(
                id="slot.arrow1",
                prompt="",
                text="→",
                style_role="body",
                x=318.0,
                y=144.0,
                font_size=34,
            ),
            TextSlot(
                id="slot.arrow2",
                prompt="",
                text="→",
                style_role="body",
                x=586.0,
                y=144.0,
                font_size=34,
            ),
            TextSlot(
                id="slot.desc1.1",
                prompt="",
                text="원 모양의 종이를",
                style_role="body",
                x=90,
                y=235,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.2",
                prompt="",
                text="둘로 똑같이 나누어",
                style_role="body",
                x=90,
                y=271,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.3",
                prompt="",
                text="지도록 접었다가 펼",
                style_role="body",
                x=90,
                y=310,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc1.4",
                prompt="",
                text="칩니다.",
                style_role="body",
                x=90,
                y=350,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.1",
                prompt="",
                text="다른 방향으로도 둘",
                style_role="body",
                x=350,
                y=235,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.2",
                prompt="",
                text="로 똑같이 나누어지",
                style_role="body",
                x=350,
                y=272,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.3",
                prompt="",
                text="도록 접었다가 펼칩",
                style_role="body",
                x=350,
                y=310,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc2.4",
                prompt="",
                text="니다.",
                style_role="body",
                x=350,
                y=350,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.1",
                prompt="",
                text="접었을 때 생기는 선",
                style_role="body",
                x=620,
                y=235,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.2",
                prompt="",
                text="분들이 만나는 점을",
                style_role="body",
                x=620,
                y=275,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.3",
                prompt="",
                text="점 ㅇ이라고 표시합",
                style_role="body",
                x=620,
                y=310,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.desc3.4",
                prompt="",
                text="니다.",
                style_role="body",
                x=620,
                y=350,
                font_size=25,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.q",
                prompt="",
                text="(2) 원을 둘로 똑같이 나누는 선분은 (반지름, 지름)입니다.",
                style_role="question",
                x=90,
                y=455,
                font_size=28,
                fill="#111111",
            ),
            TextSlot(
                id="slot.item1.q.copy3.copy1",
                prompt="",
                text="ㅇ",
                x=750,
                y=135,
                font_size=20,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008696",
    "problem_type": "geometry_circle_fold",
    "metadata": {
        "language": "ko",
        "question": "원을 둘로 똑같이 나누는 선분의 이름을 고르는 문제",
        "instruction": "알맞은 말을 선택하세요.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle", "type": "circle"},
            {"id": "obj.fold_line", "type": "segment"},
            {"id": "obj.center", "type": "point"},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle", "obj.fold_line", "obj.center"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.divide_circle_equally", "rel.intersects_at_center"],
            },
            "plan": {
                "method": "concept_choice",
                "description": "그림에서 원을 둘로 똑같이 나누는 선분의 개념과 맞는 말을 고른다.",
            },
            "execute": {"expected_operations": ["identify_shape_property", "match_geometry_term"]},
            "review": {"check_methods": ["term_consistency_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "geometry_term", "description": "원을 둘로 똑같이 나누는 선분의 이름"},
        "value": "지름",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008696",
    "problem_type": "geometry_circle_fold",
    "inputs": {
        "total_ticks": 0,
        "target_label": "원을 둘로 똑같이 나누는 선분의 이름",
        "target_ticks": 0,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle", "value": {"type": "circle"}},
        {"ref": "obj.fold_line", "value": {"type": "segment"}},
        {"ref": "obj.center", "value": {"type": "point"}},
    ],
    "target": {"ref": "answer.target", "type": "geometry_term"},
    "method": "concept_choice",
    "plan": [
        "그림에서 원을 접었을 때 원이 둘로 똑같이 나뉘는지 확인한다.",
        "그 성질에 맞는 선분의 이름을 선택한다.",
    ],
    "steps": [
        {
            "id": "step.1",
            "expr": "원은 중심을 지나며 둘로 똑같이 나뉘는 선분과 관련된다.",
            "value": "geometry_property",
        },
        {"id": "step.2", "expr": "선택지에서 해당하는 용어를 찾는다.", "value": "지름"},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "원을 둘로 똑같이 나누는 선분인지 확인",
            "expected": "true",
            "actual": "true",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {"type": "geometry_term", "description": "원을 둘로 똑같이 나누는 선분의 이름"},
        "value": "지름",
        "unit": "",
    },
}
