from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008711",
        title="연필심을 넣어야 하는 구멍 찾기",
        canvas=Canvas(width=960, height=428, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.stem",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.q1",
                    "slot.q2",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.box",
                    "slot.hole1",
                    "slot.hole3",
                    "slot.hole4",
                    "slot.hole5",
                    "slot.hole6",
                    "slot.emph",
                    "slot.arrow1",
                    "slot.arrow2",
                    "slot.arrow3",
                    "slot.arrow4",
                    "slot.arrow5",
                    "slot.lb1",
                    "slot.lb2",
                    "slot.lb3",
                    "slot.lb4",
                    "slot.lb5",
                    "slot.choice",
                ),
            ),
            Region(id="region.answer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.q1",
                prompt="",
                text="띠 종이를 누름 못으로 고정한 다음 연필심을 구멍에 끼려고 합니다.",
                style_role="question",
                x=42.0,
                y=34.0,
                font_size=28,
            ),
            TextSlot(
                id="slot.q2",
                prompt="",
                text="원을 가장 작게 그릴 때 연필심을 넣어야 하는 구멍의 기호를\n선택하세요.  ",
                style_role="question",
                x=40,
                y=66,
                font_size=28,
                fill="#111111",
            ),
            RectSlot(
                id="slot.box",
                prompt="",
                x=265,
                y=135,
                width=300,
                height=55,
                fill="#D9D9D9",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.hole1",
                prompt="",
                cx=290,
                cy=160,
                r=5,
                fill="#FFFFFF",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.hole3",
                prompt="",
                cx=375,
                cy=160,
                r=5,
                fill="#FFFFFF",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.hole4",
                prompt="",
                cx=425,
                cy=160,
                r=5,
                fill="#FFFFFF",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.hole5",
                prompt="",
                cx=470,
                cy=160,
                r=5,
                fill="#FFFFFF",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.hole6",
                prompt="",
                cx=515,
                cy=160,
                r=5,
                fill="#FFFFFF",
                stroke="#222222",
                stroke_width=1.2,
            ),
            CircleSlot(
                id="slot.emph",
                prompt="",
                cx=320,
                cy=159,
                r=10,
                fill="#111827",
                stroke="#9E9E9E",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.arrow1",
                prompt="",
                x1=375,
                y1=180,
                x2=375,
                y2=205,
                stroke="#222222",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.arrow2",
                prompt="",
                x1=425,
                y1=180,
                x2=425,
                y2=205,
                stroke="#222222",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.arrow3",
                prompt="",
                x1=290,
                y1=180,
                x2=290,
                y2=205,
                stroke="#222222",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.arrow4",
                prompt="",
                x1=470,
                y1=180,
                x2=470,
                y2=205,
                stroke="#222222",
                stroke_width=1.2,
            ),
            LineSlot(
                id="slot.arrow5",
                prompt="",
                x1=515,
                y1=180,
                x2=515,
                y2=205,
                stroke="#222222",
                stroke_width=1.2,
            ),
            TextSlot(
                id="slot.lb1",
                prompt="",
                text="ㄱ",
                style_role="label",
                x=275,
                y=245,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb2",
                prompt="",
                text="ㄴ",
                style_role="label",
                x=360,
                y=245,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb3",
                prompt="",
                text="ㄷ",
                style_role="label",
                x=410,
                y=245,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb4",
                prompt="",
                text="ㄹ",
                style_role="label",
                x=455,
                y=245,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.lb5",
                prompt="",
                text="ㅁ",
                style_role="label",
                x=500,
                y=245,
                font_size=30,
                fill="#111111",
            ),
            TextSlot(
                id="slot.choice",
                prompt="",
                text="( ㄱ , ㄴ , ㄷ , ㄹ , ㅁ )",
                style_role="label",
                x=275,
                y=330,
                font_size=30,
                fill="#111111",
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008711",
    "problem_type": "선택",
    "metadata": {
        "language": "ko",
        "question": "띠 종이를 누름 못으로 고정한 다음 연필심을 구멍에 끼려고 합니다. 원을 가장 작게 그릴 때 연필심을 넣어야 하는 구멍의 기호를 선택하세요.",
        "instruction": "구멍의 기호를 선택한다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.paper_strip", "type": "paper_strip"},
            {"id": "obj.pin", "type": "fixed_point", "description": "누름 못"},
            {"id": "obj.holes", "type": "set_of_holes", "count": 5},
            {"id": "obj.choice_labels", "type": "labels", "labels": ["ㄱ", "ㄴ", "ㄷ", "ㄹ", "ㅁ"]},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.pin", "obj.holes"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.nearest_hole"],
            },
            "plan": {
                "method": "nearest_selection",
                "description": "누름 못에 가장 가까운 구멍을 고른다.",
            },
            "execute": {"expected_operations": ["compare_distances", "select_nearest_hole"]},
            "review": {"check_methods": ["closest_position_check"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_hole_symbol",
            "description": "연필심을 넣어야 하는 구멍의 기호",
        },
        "value": "ㄱ",
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008711",
    "problem_type": "선택",
    "inputs": {
        "total_ticks": 5,
        "target_label": "연필심을 넣어야 하는 구멍의 기호",
        "target_ticks": 1,
        "target_count": 1,
        "unit": "",
    },
    "given": [
        {"ref": "obj.pin", "value": {"type": "fixed_point"}},
        {"ref": "obj.holes", "value": {"count": 5}},
    ],
    "target": {"ref": "answer.target", "type": "selected_hole_symbol"},
    "method": "nearest_selection",
    "plan": ["누름 못과 각 구멍의 가까움을 비교한다.", "가장 가까운 구멍의 기호를 고른다."],
    "steps": [{"id": "step.1", "expr": "누름 못에서 가장 가까운 구멍을 확인한다.", "value": "ㄱ"}],
    "checks": [
        {
            "id": "check.1",
            "expr": "선택된 기호가 가장 가까운 구멍의 기호와 같은지 확인한다.",
            "expected": "ㄱ",
            "actual": "ㄱ",
            "pass": True,
        }
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "selected_hole_symbol",
            "description": "연필심을 넣어야 하는 구멍의 기호",
        },
        "value": "ㄱ",
        "unit": "",
    },
}
