from __future__ import annotations
from modu_math.dsl import Canvas, ProblemTemplate, Region, TextSlot, RectSlot, CircleSlot, LineSlot


def build_problem_template() -> ProblemTemplate:
    return ProblemTemplate(
        id="S3_초등_3_008710",
        title="원을 그린 규칙을 찾아 알맞은 것을 선택하세요",
        canvas=Canvas(width=944.0, height=695.0, coordinate_mode="logical"),
        regions=(
            Region(
                id="region.top",
                role="stem",
                flow="absolute",
                slot_ids=(
                    "slot.title",
                    "slot.graphpaper.v0",
                    "slot.graphpaper.v1",
                    "slot.graphpaper.v2",
                    "slot.graphpaper.v3",
                    "slot.graphpaper.v4",
                    "slot.graphpaper.v5",
                    "slot.graphpaper.v6",
                    "slot.graphpaper.v7",
                    "slot.graphpaper.v8",
                    "slot.graphpaper.v9",
                    "slot.graphpaper.v10",
                    "slot.graphpaper.v11",
                    "slot.graphpaper.v12",
                    "slot.graphpaper.h0",
                    "slot.graphpaper.h1",
                    "slot.graphpaper.h2",
                    "slot.graphpaper.h3",
                    "slot.graphpaper.h4",
                    "slot.graphpaper.h5",
                    "slot.graphpaper.h6",
                    "slot.graphpaper.h7",
                    "slot.graphpaper.h8",
                    "slot.graphpaper.h9",
                    "slot.graphpaper.h10",
                    "slot.graphpaper.h11",
                    "slot.graphpaper.h12",
                    "slot.graphpaper.h13",
                    "slot.graphpaper.h14",
                    "slot.graphpaper.h15",
                    "slot.graphpaper.h16",
                    "slot.graphpaper.h17",
                ),
            ),
            Region(
                id="region.diagram",
                role="diagram",
                flow="absolute",
                slot_ids=(
                    "slot.circle.top",
                    "slot.circle.mid",
                    "slot.circle.bot",
                    "slot.pt.top",
                    "slot.pt.mid",
                    "slot.pt.bot",
                ),
            ),
            Region(
                id="region.rule",
                role="body",
                flow="absolute",
                slot_ids=("slot.rule_box", "slot.rule_1", "slot.rule_2"),
            ),
            Region(id="region.footer", role="answer", flow="absolute", slot_ids=()),
        ),
        slots=(
            TextSlot(
                id="slot.title",
                prompt="",
                text="원을 그린 규칙을 찾아 알맞은 것을 선택하세요.",
                style_role="question",
                x=11.0,
                y=30.0,
                font_size=28,
            ),
            CircleSlot(
                id="slot.circle.top",
                prompt="",
                cx=449,
                cy=161,
                r=83,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.circle.mid",
                prompt="",
                cx=448,
                cy=330,
                r=83,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(
                id="slot.circle.bot",
                prompt="",
                cx=449,
                cy=245,
                r=83,
                fill="none",
                stroke="#222222",
                stroke_width=1.5,
            ),
            CircleSlot(id="slot.pt.top", prompt="", cx=450, cy=160, r=5, fill="#E91E63"),
            CircleSlot(id="slot.pt.mid", prompt="", cx=450, cy=245, r=5, fill="#E91E63"),
            CircleSlot(id="slot.pt.bot", prompt="", cx=449, cy=329, r=5, fill="#E91E63"),
            RectSlot(
                id="slot.rule_box",
                prompt="",
                x=15,
                y=560,
                width=830,
                height=120,
                fill="none",
                stroke="#FFA64D",
                stroke_width=1.5,
            ),
            TextSlot(
                id="slot.rule_1",
                prompt="",
                text="원의 중심이 ( 아래쪽 , 오른쪽 )으로 모든 3칸씩 옮겨 가고",
                style_role="body",
                x=75,
                y=610,
                font_size=30,
            ),
            TextSlot(
                id="slot.rule_2",
                prompt="",
                text="원의 반지름이 모든 ( 2, 3, 6 )칸으로 같게 그린 규칙입니다.",
                style_role="body",
                x=70,
                y=655,
                font_size=30,
            ),
            LineSlot(
                id="slot.graphpaper.v0",
                prompt="",
                x1=280,
                y1=50,
                x2=280,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v1",
                prompt="",
                x1=308,
                y1=50,
                x2=308,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v2",
                prompt="",
                x1=336,
                y1=50,
                x2=336,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v3",
                prompt="",
                x1=364,
                y1=50,
                x2=364,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v4",
                prompt="",
                x1=392,
                y1=50,
                x2=392,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v5",
                prompt="",
                x1=420,
                y1=50,
                x2=420,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v6",
                prompt="",
                x1=448,
                y1=50,
                x2=448,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v7",
                prompt="",
                x1=476,
                y1=50,
                x2=476,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v8",
                prompt="",
                x1=504,
                y1=50,
                x2=504,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v9",
                prompt="",
                x1=532,
                y1=50,
                x2=532,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v10",
                prompt="",
                x1=560,
                y1=50,
                x2=560,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v11",
                prompt="",
                x1=588,
                y1=50,
                x2=588,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.v12",
                prompt="",
                x1=616,
                y1=50,
                x2=616,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h0",
                prompt="",
                x1=280,
                y1=50,
                x2=616,
                y2=50,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h1",
                prompt="",
                x1=280,
                y1=78,
                x2=616,
                y2=78,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h2",
                prompt="",
                x1=280,
                y1=106,
                x2=616,
                y2=106,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h3",
                prompt="",
                x1=280,
                y1=134,
                x2=616,
                y2=134,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h4",
                prompt="",
                x1=280,
                y1=162,
                x2=616,
                y2=162,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h5",
                prompt="",
                x1=280,
                y1=190,
                x2=616,
                y2=190,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h6",
                prompt="",
                x1=280,
                y1=218,
                x2=616,
                y2=218,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h7",
                prompt="",
                x1=280,
                y1=246,
                x2=616,
                y2=246,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h8",
                prompt="",
                x1=280,
                y1=274,
                x2=616,
                y2=274,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h9",
                prompt="",
                x1=280,
                y1=302,
                x2=616,
                y2=302,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h10",
                prompt="",
                x1=280,
                y1=330,
                x2=616,
                y2=330,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h11",
                prompt="",
                x1=280,
                y1=358,
                x2=616,
                y2=358,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h12",
                prompt="",
                x1=280,
                y1=386,
                x2=616,
                y2=386,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h13",
                prompt="",
                x1=280,
                y1=414,
                x2=616,
                y2=414,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h14",
                prompt="",
                x1=280,
                y1=442,
                x2=616,
                y2=442,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h15",
                prompt="",
                x1=280,
                y1=470,
                x2=616,
                y2=470,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h16",
                prompt="",
                x1=280,
                y1=498,
                x2=616,
                y2=498,
                stroke="#2563eb",
                stroke_width=1,
            ),
            LineSlot(
                id="slot.graphpaper.h17",
                prompt="",
                x1=280,
                y1=526,
                x2=616,
                y2=526,
                stroke="#2563eb",
                stroke_width=1,
            ),
        ),
        diagrams=(),
        groups=(),
        constraints=(),
        tags=(),
    )


PROBLEM_TEMPLATE = build_problem_template()

SEMANTIC_OVERRIDE = {
    "problem_id": "S3_초등_3_008710",
    "problem_type": "도형_규칙_찾기",
    "metadata": {
        "language": "ko",
        "question": "원을 그린 규칙을 찾아 알맞은 것을 선택하세요.",
        "instruction": "그림과 문장을 대응하여 규칙을 찾는 문제이다.",
    },
    "domain": {
        "objects": [
            {"id": "obj.circle_sequence", "type": "circle_sequence", "count": 3},
            {"id": "obj.center_shift", "type": "movement", "direction": "아래쪽", "step": 3},
            {"id": "obj.radius_rule", "type": "radius_rule", "value": 3},
        ],
        "relations": [],
        "problem_solving": {
            "understand": {
                "given_refs": ["obj.circle_sequence"],
                "target_ref": "answer.target",
                "condition_refs": ["rel.sequence_shift", "rel.sequence_same_size"],
            },
            "plan": {
                "method": "규칙_판별",
                "description": "그림에서 중심의 이동 방향과 반지름의 칸 수를 읽어 규칙을 확인한다.",
            },
            "execute": {"expected_operations": ["방향_확인", "칸수_확인"]},
            "review": {"check_methods": ["그림_문장_대응_확인"]},
        },
    },
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "도형의_그리기_규칙",
            "description": "원의 중심이 이동한 방향과 반지름의 칸 수",
        },
        "value": 3,
        "unit": "",
    },
}

SOLVABLE = {
    "schema": "modu.solvable.v1.1",
    "problem_id": "S3_초등_3_008710",
    "problem_type": "도형_규칙_찾기",
    "inputs": {
        "total_ticks": 0,
        "target_label": "원의 그린 규칙",
        "target_ticks": 0,
        "target_count": 3,
        "unit": "",
    },
    "given": [
        {"ref": "obj.circle_sequence", "value": {"count": 3}},
        {"ref": "obj.center_shift", "value": {"direction": "아래쪽", "step": 3}},
        {"ref": "obj.radius_rule", "value": {"value": 3}},
    ],
    "target": {"ref": "answer.target", "type": "도형의_그리기_규칙"},
    "method": "규칙_판별",
    "plan": [
        "그림에서 원의 중심이 어느 방향으로 같은 간격만큼 이동하는지 확인한다.",
        "원들의 반지름이 모두 같은지 확인한다.",
        "보이는 선택지와 해설을 참고해 규칙을 정리한다.",
    ],
    "steps": [
        {"id": "step.1", "expr": "중심 이동 방향 확인", "value": "아래쪽"},
        {"id": "step.2", "expr": "이동 칸 수 확인", "value": 3},
        {"id": "step.3", "expr": "반지름 칸 수 확인", "value": 3},
    ],
    "checks": [
        {
            "id": "check.1",
            "expr": "중심이 아래쪽으로 이동하는가",
            "expected": "아래쪽",
            "actual": "아래쪽",
            "pass": True,
        },
        {
            "id": "check.2",
            "expr": "반지름이 모두 3칸인가",
            "expected": 3,
            "actual": 3,
            "pass": True,
        },
    ],
    "answer": {
        "blanks": [],
        "choices": [],
        "answer_key": [],
        "target": {
            "type": "도형의_그리기_규칙",
            "description": "원의 중심이 이동한 방향과 반지름의 칸 수",
        },
        "value": 3,
        "unit": "",
    },
}
